"""V109 neutral apparatus rules: source-differentiated class projection.

These rules contain no archetype answers, evaluator findings, expected counts,
prior scored outputs, calibration answers, or holdout material.
"""
from researcher_inventory.inventory_apparatus import BASE_RULES as APPARATUS_BASE_RULES, CLASS_RULES as APPARATUS_CLASS_RULES

V109_CORRECTION = r'''
V109 PROSPECTIVE CORRECTION — SOURCE-DIFFERENTIATED CLASS PROJECTION.

READ THE WHOLE SOURCE FIRST. Silently map represented situations and relations: current episodes, interactions, attempts, waits, responses, movements, states, conversations, reports, memories, comparisons, questions, decisions, intentions, alternatives, recurring relations, prospective situations, and present telling/reflection. This map is an omission aid, not a primitive generator.

TWO-GATE ADMISSION: retain a primitive only when (A) the source establishes a complete class-native identity at a natural literal span, except legitimate unnamed PLACE/TIME support may use null source_wording with an exact source cue, and (B) the source separately projects that candidate as a participant, referential/content handle, characterization/state, event/state/relation predicate, scene/phase support coordinate, or orientation.

NO NECESSITY TEST. A coordinate does not need to be indispensable to understanding or reconstructing a frame. Do not prune it because the scene remains intelligible without it, because it is mundane, one-use, background, reported, remembered, prospective, subtle, nested, neutral, or low-salience. Preserve source-differentiated class projections even when a broad summary could omit them.

REJECT ONLY NON-PROJECTIONS: pure grammar/auxiliary/tense/aspect support with no independent class job; discourse or narration carriage with no independently represented relation/state; stylistic/rhetorical/intensifying wording with no separately represented characterization/state; a clause/proposition wrapper whose semantic work is already carried by smaller retained coordinates; a true duplicate projection of the same semantic job; or wording whose apparent class identity comes only from lexical or grammatical pointability.

MANDATORY PROJECTION SPLITTING: before admission, split clause-sized source material into the smallest complete class-native projections. If a clause contains a relation plus a separately represented characterization, object/content handle, orientation, or support coordinate, keep those jobs separately rather than swallowing them into one oversized primitive. Projection splitting is not token decomposition: preserve required particles, complements, reflexives, negation, modality, uncertainty, attribution, comparison, idiom/dialect, and other material required to keep the primitive semantically complete.

FUNCTION BEFORE FORM:
- represented human/social participant -> PERSON;
- separately reified concrete/abstract/internal/relational/content/decision/value/category/figurative handle -> OBJECT;
- represented characterization/state/identity/evaluation/comparison/correction/polarity/manner/posture -> LABEL;
- source-differentiated scene/location support -> PLACE;
- source-differentiated episode/period/phase support -> TIME;
- distinct source-present event/state/relation predicate -> VERB;
- separately represented orientation that situates a retained node/relation/scene -> LOCATOR.
Surface grammar does not decide class. Cross-class overlap is allowed only when the same exact span genuinely performs two distinct source-present jobs.

PLACE/TIME — EVENT/PHASE SUPPORT INDEXING: after mapping source-differentiated episodes/phases, preserve the support coordinates the source establishes, including legitimate neutral unnamed support. A support coordinate qualifies because the source differentiates a scene/phase or situates a represented relation there; it does not need to be indispensable. Broad and local support may coexist when they do different support jobs. Merge only when multiple cues genuinely identify the same support coordinate. Do not infer geography/chronology and do not inventory physical nouns, destination phrases, temporal tokens, durations, recurrence words, transitions, tense, or actions.

PERSON: retain the speaker and every distinct source-established human/social actor or stable group participating in, possessing within, remembered/reported within, producing/receiving content within, or prospectively involved in represented structure. One-use, offscreen, possessive, relational, institutional, remembered, reported, and prospective actors may qualify. Merge aliases/coreference. Reject rhetorical/generic/nonreferential addressees.

OBJECT: retain each concrete, abstract, internal, relational, decision/choice-like, value-like, set/category, reported-content, or figurative handle when the source separately treats it as a thing/content coordinate. A handle may qualify because it is acted on, possessed, exchanged, checked, contrasted, questioned, remembered, reported, selected, decided about, located, valued, named as content, or otherwise reified. Nested and one-use handles may qualify. Reject noun census, generic pronouns/deixis, discourse topics, arbitrary nominalizations, and proposition wrappers that merely package other retained coordinates.

LABEL: retain the smallest complete source-native characterization when the source assigns or presents a quality, state, identity, evaluation, comparison, candidate/question label, correction, acceptance/rejection, polarity, manner, or posture. A LABEL can be subtle, idiomatic, colloquial, negated, uncertain, figurative, comparative, or one-use. Do not require salience or indispensability. Reject only descriptive color, intensification, rhetorical flourish, or modifier vocabulary that does not establish a separately represented characterization/state.

VERB: retain the smallest complete source-supported predicate/relation span whenever the source separately presents a distinct event/state/relation. Eligible relations include simple actions and states, attempts, responses, movement, location/state relations, possession, perception, communication/report, cognition, intention, questions, decisions, comparison, evaluation, transitions, and other source-present relations. Do not drop a simple or carrier-like relation merely because its content/state can also be represented by another coordinate. Reject auxiliaries and tense/aspect support with no independent relation job; pure grammatical shells whose semantic work is exhausted by another retained projection; narration/discourse organizers with no separately represented relation; redundant restatements; and oversized proposition wrappers that should be split into a smaller relation plus separate OBJECT/LABEL/LOCATOR/support coordinates. Choose the natural relation span: do not shrink below required particles/complements, but do not swallow independently typed complements merely to make a larger predicate.

LOCATOR: retain a LOCATOR when an exact source span separately situates a retained node, event/state relation, or scene by spatial position, containment, path, direction, origin/destination, proximity, accompaniment/carrying, recurrence, procedure/relation, internal/mental context, temporal position, or figurative/comparative orientation. It does not need to be indispensable under removal. Reject bare prepositions, ordinary argument/topic markers, discourse connectors, duplicate deictics, TIME-duplicate duration phrases, and free-standing spatial/temporal wording with no separate orienting job.

ATOMIC SPAN + LITERAL LOCK: after admission and class resolution use the smallest complete exact contiguous source-native span. Preserve required particles/prepositions, reflexives, essential complements, negation, modality, uncertainty, questions, attribution, comparison, idiom/dialect, and hypothetical/prospective/reported/corrective posture. Never normalize, paraphrase, clean up, lemmatize into a different surface form, or substitute synonyms. Neutral mechanical tags are reserved only for legitimate unnamed PLACE/TIME support and must be anchored by exact source cues.

FREEZE AUDITS: (1) whole-source situation map; (2) projection-splitting audit; (3) event/phase support indexing; (4) class-native projection audit; (5) anti-wrapper audit; (6) anti-census/grammar/discourse/style audit; (7) functional-class audit; (8) atomic-span audit; (9) literal-lock audit; (10) semantic-deduplication audit. Repeat until stable before compounds.

RELATION-INSTANCE COMPOUND COMPLETENESS: only after all primitives are frozen, reread the source relation by relation. For each distinct retained VERB relation instance, emit the smallest complete compound connecting the frozen coordinates that participate in that exact relation, including applicable participant/content/support/orientation/characterization refs when part of that relation. Additional non-VERB compounds are allowed only when the source separately represents a relation/state structure not already captured by a retained VERB relation compound. Nested or overlapping compounds may coexist when they represent different source-present relations. Do not emit graph closure, every possible pair, arbitrary co-occurrence bundles, singleton equivalents, generic question closure, duplicate restatements, subset/superset permutations of the same relation, or scene mega-bundles. Compounds never justify primitive defects.

Never target hidden counts or infer hidden gold. Never expose approved archetypes, evaluator findings, prior scored outputs, calibration answers, or sealed holdout material. Never perform promotion, Oval Office admission, APA-ID creation, sovereign/admitted writing, or database mutation.
'''.strip()

V109_BASE_RULES = APPARATUS_BASE_RULES + "\n\n" + V109_CORRECTION
V109_CLASS_RULES = dict(APPARATUS_CLASS_RULES)
V109_CLASS_RULES.update({
    "PLACE": "Retain each distinct source-established scene/location support coordinate for a source-differentiated episode or relation. A support coordinate need not be indispensable. Broad and local support may coexist only when they do different support jobs. Supported unnamed PLACE may use null source_wording with exact source_cue and a neutral tag. Reject physical/spatial wording that is merely referential, orienting, incidental, or token-level rather than a support coordinate.",
    "TIME": "Retain each distinct source-established episode/period/phase support coordinate, including legitimate remembered, reported, recurring, prospective, and present-reflection support. A support coordinate need not be indispensable. Merge cues doing the same support job. Supported unnamed TIME may use null source_wording with exact source_cue and a neutral tag. Reject temporal-token, duration, tense, transition, or one-time-per-action census behavior.",
    "PERSON": "Retain the speaker and each distinct represented human/social actor or stable group after true coreference when the source establishes that actor in represented structure. One-use, offscreen, possessive, remembered, reported, institutional, relational, and prospective actors may qualify. Reject rhetorical/generic/nonreferential addressees.",
    "OBJECT": "Retain each separately represented concrete, abstract, internal, relational, decision/choice-like, value-like, set/category, represented-content, or figurative handle. A handle may qualify because it is acted on, possessed, checked, contrasted, questioned, remembered, reported, selected, decided about, located, valued, named as content, or otherwise reified. Reject noun census, generic pronouns/deixis, discourse topics, arbitrary nominalizations, incidental wording, and proposition wrappers without independent handle identity.",
    "LABEL": "Retain each distinct source-present characterization/state/identity/evaluation/comparison/correction/polarity/manner/posture that the source separately assigns or presents. Local, one-use, idiomatic, figurative, comparative, uncertain, negated, and colloquial characterizations may qualify without an indispensability test. Reject intensifier/modifier/colorful-language/rhetorical census and wording with no independently represented characterization/state.",
    "VERB": "Retain each smallest complete source-supported event/state/relation predicate that the source separately presents, including simple actions/states, possession, perception, communication/report, cognition, intention, questions, decisions, comparisons, evaluations, movement, location/state relations, and transitions. Reject auxiliaries, tense/aspect support, grammar-only shells, narration/discourse organizers with no represented relation, redundant restatements, and oversized proposition wrappers. Split independently typed complements instead of swallowing them into the VERB, while preserving particles/complements required for the relation itself.",
    "LOCATOR": "Retain each distinct smallest complete orientation the source separately uses to situate a retained node, relation, or scene, including spatial position, containment, path, direction, origin/destination, proximity, accompaniment, recurrence, procedure/relation, internal/mental context, temporal position, and figurative/comparative orientation. Reject bare prepositions, ordinary argument/topic markers, discourse connectors, duplicate deictics, TIME-duplicate duration phrases, and free-standing orientation wording with no separate orienting job.",
})
