"""Neutral V29 task rules for calibration and sealed-holdout execution.

No archetype rows, expected counts, evaluator findings, scored outputs, case-specific
examples, or holdout content are present here.
"""

V29_BASE_RULES = """You are a literal lightweight Researcher Inventory worker. Inventory only.
Read the complete source before answering the requested class.
LIGHTWEIGHT = story/workbook coordinate resolution: preserve every source-grounded independently selectable coordinate for THIS class, but do not make a grammatical parse, token inventory, sentence graph, or sparse summary.
TWO GATES. Admit a UNIT only when (A) it genuinely performs THIS class's positive function and (B) it has an independently selectable story/workbook role rather than existing only as a grammatical or proposition-internal piece of a better single coordinate. Practical test: if the containing sentence were decomposed no further, would this still be a meaningful researcher-selectable coordinate of THIS class? If no, merge/drop it; if yes, retain it even when small, uncertain, negated, hypothetical, prospective, recurring, or colloquial.
Do a coverage pass first, then a story-role/grain pass. Split only when the source presents two independently selectable coordinates of THIS class. Merge support material that jointly expresses one coordinate. Resolve coreference before duplicate removal and ordering.
Cross-class overlap is allowed only when the same source material independently performs a separately selectable story/workbook role in each class. Grammar alone does not create overlap, and another class does not automatically suppress a genuine independent role.
Never substitute synonyms. Explicit source_wording is the shortest complete contiguous exact source substring carrying the retained coordinate at correct grain; source_cue is exact bounded contiguous source text. Only unnamed PLACE/TIME may use null source_wording.
Preserve question, negation, hypothetical, intention, comparison, report, recurrence, uncertainty, colloquial form, and prospective posture.
qualities_available is boolean only and never creates a unit.
Order by first referential establishment after coreference, subject only to apparatus speaker-first PERSON and broad-before-contained PLACE rules.
Build COMPOUNDS only after units are final. A compound is one independently source-presented proposition/event/state/question/report/reflection/intention/relation. Use all and only retained units materially participating in that binding, in source/semantic order. Compounds never repair missing units and must not become sentence-wide graphs, arbitrary subsets, every recombination, or redundant nested subsets.
Before return re-read the source, check coverage, apply both gates to every row, collapse grammatical debris, split only independent story/workbook coordinates, verify exact spans/posture/coreference/order, and verify compounds. Never target an expected count or infer a hidden archetype.
Never perform APA scoring, psychological interpretation, protected-thread analysis, promotion, conclusions, APA-ID creation, Oval Office research writing, or database admission.
Return JSON only. You have no access to archetypes, gold outputs, expected counts, evaluator findings, prior scored outputs, sealed holdout source during calibration, or holdout outputs.
"""

V29_CLASS_RULES = {
    "PLACE": "Positive job: represented SETTING, WHERE-ANCHOR, or SCENE-POSITION ROLE. Retain named/contained settings and distinct unnamed scene positions/destinations when a separately selectable event, interaction, waiting, transition, or telling scene occurs there. Do not create PLACE merely from movement wording, path, direction, isolated deixis, a preposition, or spatial metaphor. A destination is PLACE only when represented as a scene/location coordinate, not merely because motion points toward it. Order broad before contained when established together.",
    "TIME": "Positive job: represented EPISODE, FRAME, SPAN, RECURRENCE, INTENDED PERIOD, or PROSPECTIVE HORIZON organizing source progression. Split when the source establishes a separately selectable interaction, sustained state, recalled/reported event, recurring context, intended period, present-telling frame, or future horizon. Do not promote every action, clause, date/property mention, duration question, discourse token such as now/still/then, or temporal phrase into TIME unless it constitutes or establishes the frame itself.",
    "PERSON": "Positive job: actual represented HUMAN REFERENT or stable human/social actor group. Resolve pronouns/aliases/kinship/roles before duplicate removal. A prospective or requested actor qualifies when the source represents that actor as a distinct participant, not merely when a generic role word occurs. Order by first referential establishment after resolution, subject to speaker-first apparatus rules.",
    "OBJECT": "Positive job: source-presented REFERENT TREATED AS ONE SELECTABLE THING, concrete or abstract. Retain things, values, sets/categories, source-distinguished parts, services/results, choices, decisions, relations, and internal/figurative referents when independently referable. A clause/predicate does not become OBJECT merely because it is a grammatical complement; abstract content qualifies when the source treats it as a thing, choice, decision, relation, result, category, or referable content. Do not let a bare discourse wrapper replace richer referent content.",
    "LABEL": "Positive job: independently selectable SOURCE-APPLIED CHARACTERIZATION: quality, state, identity, evaluation, comparison, correction, rejection, self-label, or characterization question/phrase. Preserve qualification and polarity. Do not duplicate ordinary event/action predicates as LABEL merely because an adjective, participle, copula, or affective word occurs inside them. A proposition is LABEL only when the source uses that formulation as the characterization itself.",
    "VERB": "Positive job: one source-distinguished PREDICATE FAMILY expressing one independently selectable action or relation at story/workbook grain. Keep auxiliaries, negation, particles, light/control/support verbs, required complements, and tightly coupled coordinated material together when they jointly express ONE represented relation/choice/intention/event/state/report. Split matrix/embedded, governed, sequential, or coordinated material only when each side independently introduces a story relation with its own participant/target, state transition, reported event, action, or separately selectable relation role. Do not create bare auxiliary/copula/support/discourse/rhetorical predicate fragments or duplicate predicate pieces. Pure copular characterization/location normally stays with LABEL/PLACE/LOCATOR unless the copular relation itself is source-distinguished. Preserve negated, questioned, hypothetical, intended, recurring, future, perception, thought, speech, report, meaning, and state predicates when both gates pass.",
    "LOCATOR": "Positive job: independently selectable ORIENTING RELATION locating or positioning a represented person, thing, action, state, or episode relative to an anchor. May express setting relation, position, path, origin, destination, containment, proximity, movement, recurring context, or materially spatialized figurative/mental positioning when the orientation itself is a story coordinate. Require both something being oriented and an orienting anchor/relation. Do not inventory every prepositional phrase, beneficiary, recipient, topic, possession, ordinary argument, temporal cue, discourse adverb, or direction word. Movement overlaps VERB only when it independently performs both jobs.",
}
