"""Neutral V55 task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v53_task_rules import V53_BASE_RULES, V53_CLASS_RULES

V55_DELTA = """
V55 BALANCED COORDINATE-IDENTITY CORRECTION: preserve V53 relation integrity and the valid V54 lesson that nesting, unnamed status, or grammatical dependence do not automatically exclude a source coordinate. However, semantic separability is not primitive identity. Admit a unit only when, after coreference and local context are restored, the source itself establishes a stable reusable coordinate of the requested class that a researcher could independently revisit. A syntactic subpredicate, modifier, relation argument, deictic wrapper, action-local implicit frame, physical subposition, or orientation phrase is not a primitive merely because it can be semantically isolated. Use source-distinction and dependency ledgers: retain source-established distinctions; collapse candidates that exist only as decompositions of another coordinate. PLACE: keep independent physical scenes/occurrence positions, including supported unnamed interaction settings, but not every surface, object part, endpoint, container, or subposition. TIME: keep reusable episode/period/frame distinctions, not every adverb, duration, simultaneity phrase, purpose, or action-local moment. PERSON: generic/impersonal/rhetorical grammatical 'you' is not a represented person absent a stable addressee. OBJECT: resolve pure deictic/anaphoric wrappers to antecedents; retain embedded content only when source-treated as a stable reusable thing. LABEL: keep independently selectable source values, not every adjective/adverb/modifier fragment. VERB: one separate primitive requires one distinct source-native lexical relation identity; do not recursively split control/infinitival/auxiliary/complement syntax merely because it contains multiple predicates. LOCATOR: wording may extend beyond a prepositional phrase, but must independently orient/place a retained coordinate or episode rather than mirror any relation argument. COMPOUNDS are selective bindings among admitted coordinates, not lossless syntax; lexical material may remain in the source without receiving its own primitive unit.
"""

V55_BASE_RULES = V53_BASE_RULES + "\n" + V55_DELTA
V55_CLASS_RULES = dict(V53_CLASS_RULES)
V55_CLASS_RULES.update({
    "PLACE": V53_CLASS_RULES["PLACE"] + " Preserve a supported unnamed interaction/occurrence setting only when the source establishes a coherent reusable scene or co-presence context. Do not promote floors, counters, walls, lines, sides, distances, surfaces, containers, or endpoints merely because a relation occurs there.",
    "TIME": V53_CLASS_RULES["TIME"] + " Preserve source-established episode/period/frame distinctions, including current reflection, remembered interaction, wait, recurrence, transition, or prospective frames when independently reusable. Do not create TIME from each temporal modifier, aspect marker, duration phrase, simultaneity phrase, question, or action-local moment.",
    "PERSON": V53_CLASS_RULES.get("PERSON", "") + " Generic, impersonal, rhetorical, idiomatic, or self-directed grammatical 'you' is not PERSON unless the source establishes a stable represented addressee.",
    "OBJECT": V53_CLASS_RULES["OBJECT"] + " Resolve pure deictic/anaphoric wrappers such as this/that/it to an established antecedent instead of creating duplicate referents. Embedded content qualifies only when the source treats it as a stable independently revisit-able thing/content.",
    "LABEL": V53_CLASS_RULES["LABEL"] + " A modifier or predicate-linked value is retained only when the complete value is independently selectable as a source characterization; do not fragment every adjective, adverb, degree marker, or negation into a label.",
    "VERB": V53_CLASS_RULES["VERB"] + " Split an embedded, reported, coordinated, or infinitival relation only when the source establishes a second independently revisitable lexical-relation identity. A grammatical subpredicate with its own participant/complement is not sufficient by itself.",
    "LOCATOR": V53_CLASS_RULES["LOCATOR"] + " LOCATOR wording need not be a prepositional phrase: destination actions, standing/placement expressions, recurrence contexts, or temporal-position expressions may qualify when they independently supply reusable orientation. Reject relation arguments that do not independently orient another retained coordinate or episode."
})
