"""Neutral V56 task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v55_task_rules import V55_BASE_RULES, V55_CLASS_RULES

V56_DELTA = """
V56 REPRESENTATION-GRAPH CORRECTION: reconstruct the source-supported represented graph before final primitive selection. Primitive admission is based on distinct representation ROLE, not surface lexical salience or grammatical independence. Preserve the smallest coordinate set that reconstructs source-distinguished actors, stable content/nodes, values, lexical-relation atoms, orientation edges, physical settings, temporal/narrative frames, and their material bindings. A supported unnamed or grammatically dependent structural anchor may qualify when omission collapses a represented scene/frame/relation distinction; a vivid noun/modifier/verb/prepositional phrase does not qualify merely because it is semantically meaningful. Build the graph from complete-source traversal, coreference, scene/frame segmentation, relation atoms, values and orientation edges; then emit only the requested class. Perform a structural-completion check so lexical extraction does not omit source-supported PLACE/TIME/context anchors. Cross-class function outranks part of speech. VERB uses smallest complete relation atoms: split when distinct source-presented graph edges remain independently meaningful; merge when tokens form one inseparable predicate/relation. LOCATOR uses smallest complete orientation edges and may retain a syntactic relation argument when it supplies a distinct position/path/accompaniment/destination/containment/origin/exit/proximity/figurative orientation role; do not automatically concatenate distinct orientation roles. LABEL preserves smallest complete value/polarity atoms, including distinct questioned/rejected/affirmed/corrected roles when source-presented, without modifier census. OBJECT retains stable concrete/abstract/mental/relation-result nodes that materially participate, not incidental noun census or duplicate proposition wrappers. PLACE/TIME are structural settings/frames for relation clusters, not every object or predicate. Compounds are material graph bindings among frozen primitives, neither lossless syntax nor combinatorial closure.
"""

V56_BASE_RULES = V55_BASE_RULES + "\n" + V56_DELTA
V56_CLASS_RULES = dict(V55_CLASS_RULES)
V56_CLASS_RULES.update({
    "PLACE": V55_CLASS_RULES["PLACE"] + " V56: decide PLACE by setting function in the represented graph, not noun category. Retain source-supported broad/contained or unnamed co-presence/occurrence settings when they anchor a distinct relation cluster. A bounded concrete support/context may be PLACE when activity is represented as occurring in/on it; do not keep it as OBJECT merely because it is concrete. Conversely, surfaces/endpoints/parts that only orient a relation remain LOCATOR or unretained.",
    "TIME": V55_CLASS_RULES["TIME"] + " V56: identify narrative/representational frames before lexical time phrases. Retain distinct earlier/later, active/waiting, remembered, current-telling/reflection, recurring, continuing, and prospective frames when they organize relation clusters. A source-supported frame may be unnamed. Do not promote every temporal phrase to TIME; a phrase that only positions a retained frame can be LOCATOR.",
    "PERSON": V55_CLASS_RULES["PERSON"] + " V56: retain only represented social actors/stable groups after coreference. Surface second-person grammar remains excluded unless it establishes a stable addressee role.",
    "OBJECT": V55_CLASS_RULES["OBJECT"] + " V56: retain stable graph nodes/content, including mental/abstract/relation-result content when source-treated as a thing, and concrete nodes only when they materially participate. Do not census incidental nouns/comparison scenery. If concrete wording primarily supplies the occurrence setting, classify it as PLACE; if wording primarily supplies a value, use LABEL.",
    "LABEL": V55_CLASS_RULES["LABEL"] + " V56: use smallest complete source-presented value/polarity atoms. Distinct questioned, rejected, corrected, affirmed, intensified, or contrasted values may be separate LABEL coordinates when they play distinct value roles. Do not merge them solely because they occur in one sentence; do not split ordinary modifiers with no independent value role.",
    "VERB": V55_CLASS_RULES["VERB"] + " V56: relation atom, not token and not whole clause, is the grain. Split two lexical relations when each contributes a distinct graph edge and either could be removed while the other remains a meaningful represented relation. Merge only when multiple words jointly form one inseparable lexical predicate/edge. Grammatical embedding/coordination is evidence neither for nor against splitting by itself.",
    "LOCATOR": V55_CLASS_RULES["LOCATOR"] + " V56: retain smallest complete orientation edges. A syntactic argument can qualify when it materially supplies position, path, direction, origin/destination, entry/exit, containment, support/surface placement, accompaniment/carrying, proximity/distance, recurrence/temporal positioning, or figurative orientation. Keep distinct orientation roles separate rather than concatenating movement plus accompaniment plus destination/context into one long locator."
})
