"""Neutral V57 apparatus task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v56_task_rules import V56_BASE_RULES, V56_CLASS_RULES

V57_DELTA = """
V57 CLASS-NATIVE COMPLETENESS CORRECTION: supersede V56's globally minimal representation-graph selection criterion. Produce a complete lightweight inventory for the requested class: first traverse the full source for every source-supported coordinate that independently performs that class job, then perform structural backfill, type-specific exclusion, grain repair, coreference/deduplication, and excess pruning. A coordinate need not be globally indispensable to a minimum graph; lexical or grammatical separability alone still does not create a coordinate. PLACE is occurrence-position/physical-scene inventory and may preserve distinct supported unnamed/co-located roles. TIME is episode/period/frame inventory, not adverb/action-moment census. PERSON preserves source-distinguished represented actors/groups after coreference, excluding generic grammatical second person. OBJECT defaults toward retaining source-distinguished stable concrete/content referents while excluding duplicate proposition/action/state wrappers. LABEL requires a foregrounded value/classification/state/evaluation/polarity role and strongly excludes ordinary modifier census. VERB preserves materially distinct complete lexical relations while excluding pure discourse/performance scaffolding and redundant grammatical fragments. LOCATOR is orientation-only and excludes duplicated TIME/PLACE frames, topical/content complements, durations/dates, and ordinary non-orienting prepositional arguments. After each class pass, check relation clusters for missing source-supported structural anchors and underrepresented people/objects before final pruning. Compounds use frozen units to encode one complete material binding skeleton per distinct source-presented relation, rejecting subset duplicates, trivial non-binding combinations, combinatorial closure, and broad sentence bags.
"""

V57_BASE_RULES = V56_BASE_RULES + "\n" + V57_DELTA
V57_CLASS_RULES = dict(V56_CLASS_RULES)
V57_CLASS_RULES.update({
    "PLACE": V56_CLASS_RULES["PLACE"] + " V57 override: do not minimize PLACE globally. Retain every source-supported independently revisitable physical scene or occurrence-position role, including distinct unnamed or co-located roles, after applying the PLACE positive-function test. Exclude material whose function is only orientation or physical-noun reference.",
    "TIME": V56_CLASS_RULES["TIME"] + " V57 override: retain source-distinguished episodes, periods, phases, remembered/current/prospective frames and broader/contained frames when each has an independent temporal role. Exclude mere discourse time words, tense/aspect, durations, and action-local moments that do not establish a reusable frame.",
    "PERSON": V56_CLASS_RULES["PERSON"] + " V57: preserve every source-distinguished represented human/social actor or stable group after coreference even when introduced indirectly, relationally, possessively, or offscreen. Exclude generic/impersonal/rhetorical second person.",
    "OBJECT": V56_CLASS_RULES["OBJECT"] + " V57 override: source-distinguished stable concrete/content referents receive a default-retain bias after coreference; do not prune them merely as background or nested detail. Exclude duplicate proposition/action/state wrappers and analyst-created nominalizations when the source does not independently reify them.",
    "LABEL": V56_CLASS_RULES["LABEL"] + " V57 override: require a foregrounded independently reusable characterization/state/value/classification/evaluation/comparison/polarity/correction role. Strongly exclude ordinary adjective/adverb/modifier/intensifier census and proposition-sized labels when a smaller complete value carries the source role.",
    "VERB": V56_CLASS_RULES["VERB"] + " V57 override: retain materially distinct complete lexical relation identities, but strongly exclude pure discourse/performance scaffolding, conversational mechanics, filler, stage-direction mechanics, and redundant clause fragments that do not independently bind a represented relation.",
    "LOCATOR": V56_CLASS_RULES["LOCATOR"] + " V57 override: orientation only. Retain independently reusable position/path/direction/origin/destination/entry/exit/containment/support/accompaniment/proximity/movement/internal-or-figurative orientation. Exclude duplicate TIME/PLACE frames, topical/content complements, beneficiary/recipient arguments, durations/dates, recurrence wording, and generic non-orienting prepositional arguments."
})
