"""Neutral V58 apparatus task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v56_task_rules import V56_BASE_RULES, V56_CLASS_RULES

V58_DELTA = """
V58 RELATION-ANCHORED SELECTION CORRECTION: supersede both V56 global-minimum selection and V57 free-standing coverage-first enumeration. First reconstruct MATERIAL REPRESENTED BINDINGS in source order, then their physical-scene and temporal-frame anchors, and only then emit the requested class. A primitive qualifies only if it fills a distinct class-native role in at least one material represented binding/frame or is a source-supported structural anchor required to preserve that binding/frame. Every retained primitive must answer: which specific material binding/frame role requires me? Remove candidates with no answer. Then inspect every material binding/frame for omitted source-distinguished roles of the requested class and backfill them. This symmetric EXCESS CHECK + GAP CHECK is the selection gate. Do not census nouns, modifiers, verbs, time phrases, prepositional phrases, conversational mechanics, or semantically separable fragments. Do not minimize away source-distinguished participants, concrete things/parts, values/classifications, lexical relation atoms, orientation edges, occurrence positions, or frames merely because a larger event can still be reconstructed. Concrete participating things receive a retain bias, including source-distinguished whole/part and container/content roles. Abstract/content objects require source reification as stable content. LABEL requires a foregrounded value/classification/state role in a material binding, not adjective census. VERB requires a material lexical relation atom, excluding filler, floor-management, performance/stage mechanics and nonbinding metacognitive scaffolding. LOCATOR includes reusable physical, movement, containment, support, accompaniment, proximity, recurrence/temporal-position, or figurative orientation edges when they materially orient a represented coordinate/binding; it is not limited to prepositions and may coexist with PLACE/TIME when both positive roles independently exist. PLACE includes source-grounded unnamed/offscreen occurrence positions when they materially anchor bindings, including object/participant positions when independently revisitable. TIME includes source-grounded episode/period/frame anchors, including present telling/reflection and prospective frames, but not every predicate or temporal word. Freeze primitives, then build one complete smallest compound per material binding using all and only frozen units materially participating in that binding. Preserve source spelling, dialect, number, punctuation and posture exactly; never normalize wording.
"""

V58_BASE_RULES = V56_BASE_RULES + "\n" + V58_DELTA
V58_CLASS_RULES = dict(V56_CLASS_RULES)
V58_CLASS_RULES.update({
    "PLACE": V56_CLASS_RULES["PLACE"] + " V58 override: derive PLACE from the binding/frame ledger, not a global-minimum graph and not a physical-noun census. Retain every distinct source-supported physical occurrence-position role that materially anchors a represented binding, including unnamed/offscreen positions and participant/object positions when independently revisitable. A concrete thing may remain OBJECT while its represented position is a separate PLACE. Exclude mere path/direction/surface/component wording when it supplies orientation or object identity but no occurrence-position role.",
    "TIME": V56_CLASS_RULES["TIME"] + " V58 override: derive TIME from binding/frame segmentation. Retain distinct episodes, periods, phases, remembered/reported frames, recurring/continuing periods, present telling/reflection and prospective frames when they organize material bindings. Exclude predicate-local moments, tense/aspect, discourse transitions, bare dates/durations or temporal wording that only positions another frame. Temporal wording may also be LOCATOR only if it independently supplies an orientation edge.",
    "PERSON": V56_CLASS_RULES["PERSON"] + " V58: retain every source-distinguished represented actor or stable group that participates in a material binding after coreference, including relational, possessive, indirect and offscreen introduction. A human-role noun used only as classification may instead be LABEL. Generic/impersonal/rhetorical second person remains excluded.",
    "OBJECT": V56_CLASS_RULES["OBJECT"] + " V58 override: retain source-distinguished concrete things, parts, components, artifacts, materials, containers/contents, supports and comparison objects when they materially participate in a binding; do not prune them for being background or nested. Retain abstract/content objects only when source-treated as stable revisitable content. Reject action/state/proposition wrappers, deictic duplicates and analyst nominalizations that do not have an independent binding role.",
    "LABEL": V56_CLASS_RULES["LABEL"] + " V58 override: retain only foregrounded value, state, classification, evaluation, comparison, identity/social-role classification, polarity, correction or question-label roles that participate materially in a binding. Noun phrases may be LABEL when used as classifications. Strongly reject ordinary modifiers, intensifiers and descriptive census. Use the shortest complete source-native value preserving polarity/posture.",
    "VERB": V56_CLASS_RULES["VERB"] + " V58 override: retain the shortest complete lexical relation atom for each material represented binding. Split only when two distinct binding jobs survive independently; merge inseparable predicate material. Exclude conversational floor-management, filler, speech-performance mechanics, stage/pantomime mechanics, discourse transitions, bare metacognitive scaffolding and syntactic subpredicates that create no independent material binding.",
    "LOCATOR": V56_CLASS_RULES["LOCATOR"] + " V58 override: retain the smallest reusable orientation edge materially positioning a coordinate/binding: physical position, path/direction, origin/destination, entry/exit, containment, support/surface, accompaniment/carrying, proximity/distance, recurrence/temporal position, or figurative/internal orientation. LOCATOR need not be prepositional. Reject topical/content complements, ordinary recipient/beneficiary arguments, bare dates/durations and generic relation arguments. Do not suppress genuine LOCATOR overlap with PLACE/TIME when both independent positive roles exist."
})
