"""Neutral V59 apparatus task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v52_task_rules import V52_BASE_RULES, V52_CLASS_RULES

V59_DELTA = """
V59 SOURCE-COORDINATE CORRECTION: primitive admission is source-coordinate-first. A primitive does not need to be indispensable to a proposition, selected material binding, or globally minimal graph. First make a complete coverage pass across the entire source for distinct source-present coordinates of the requested class, including low-salience, background, nested, reported, descriptive, scene-setting, one-use, questioned, negated, hypothetical, recurring, prospective, figurative and embedded coordinates. Then resolve PRIMARY SOURCE FUNCTION, smallest complete source-native GRAIN, coreference, and true duplicates. Remove only aliases, duplicate same-coordinate grains, pure grammar/function fragments with no class-native job, deictic/proposition wrappers that merely restate another retained coordinate, and analyst-created abstractions. Relation/binding reconstruction may be used after coverage to detect omissions and is required for compounds after primitives freeze, but binding centrality may not erase an otherwise valid source-present primitive. PLACE/TIME should preserve source-distinguished supported positions/frames, including unnamed ones, while rejecting broad analyst summary scenes/periods not separately established by the source. OBJECT may include stable choices, decisions, relations, sets/results, internal referents and concrete/background things when the source treats them as revisit-able referents; reject whole-clause/proposition wrappers. LABEL includes source-present characterization, condition, manner-state, evaluation, comparison, status, descriptive attribution, polarity and correction without requiring dramatic foregrounding; do not automatically promote an entire question/clause when a smaller value/state coordinate is the source function. VERB includes distinct source-present lexical relation increments, including embedded/reporting/perception/cognition/stance/modal/copular relations; do not create a redundant verb when the material's primary source function is already a LABEL/OBJECT/LOCATOR and no independent lexical relation remains. LOCATOR is the smallest complete source-native orientation relation; movement/destination/standing expressions may qualify as complete locators and should not be reduced to a bare deictic if that loses orientation identity. Cross-class overlap is exceptional and requires two independently positive source functions. Freeze primitives before relation/binding reconstruction. Compounds then represent distinct source-present bindings using all and only frozen units materially co-bound in that relation; primitive validity does not depend on appearing in a compound. Preserve literal source spelling, punctuation, dialect and posture exactly. Never target expected counts or infer hidden gold.
"""

V59_BASE_RULES = V52_BASE_RULES + "\n" + V59_DELTA
V59_CLASS_RULES = dict(V52_CLASS_RULES)
V59_CLASS_RULES.update({
    "PLACE": V52_CLASS_RULES["PLACE"] + " V59: preserve every distinct source-supported physical scene/occurrence-position coordinate after complete coverage, including supported unnamed waiting/standing positions, represented object whereabouts, offscreen participant destinations/positions, later/remembered interaction positions, and present-telling position when the source establishes it. Broad and contained positions may coexist only when separately source-present. Reject analyst-created umbrella scenes and physical nouns that function only as things or orientation.",
    "TIME": V52_CLASS_RULES["TIME"] + " V59: preserve distinct source-supported episodes, attempts, phases, waits, transitions, later conversations, recurring frames, present reflection, hypothetical/prospective and future frames even when brief or embedded. Do not invent an umbrella story period merely to contain events. Predicate-local moments, bare duration/deictic words and discourse transitions do not qualify by themselves.",
    "PERSON": V52_CLASS_RULES["PERSON"] + " V59: complete-source actor coverage remains controlling. Resolve aliases/coreference before pruning. Retain indirect, relational, possessive, offscreen, remembered and reported actors when source-distinguished. Exclude generic/impersonal second person without a stable represented actor role.",
    "OBJECT": V52_CLASS_RULES["OBJECT"] + " V59: retain distinct stable concrete or abstract source referents, including choices, decisions, relations, sets/results, internal referents, low-salience concrete things and source-distinguished whole/part roles. Reject clause/proposition/deictic wrappers or analyst nominalizations that merely package an already represented relation. Primary source function controls before overlap.",
    "LABEL": V52_CLASS_RULES["LABEL"] + " V59: LABEL does not require foregrounding. Retain smallest complete source-present characterization, condition, manner-state, descriptive attribution, evaluation, comparison, status, polarity or correction coordinates when they are distinct values/states. Do not automatically use an entire question/clause as LABEL when a smaller state/value is the actual coordinate; exclude mere intensifiers/function modifiers.",
    "VERB": V52_CLASS_RULES["VERB"] + " V59: retain distinct source-present lexical predicate/relation increments, including embedded, reporting, perception, cognition, stance, possession, modal/normative, copular/locative, movement and waiting relations. Split distinct relation jobs; merge inseparable lexical identity material. Exclude pure auxiliaries/filler and predicate fragments that only restate a LABEL/OBJECT/LOCATOR without an independent relation job. No proposition-centrality requirement.",
    "LOCATOR": V52_CLASS_RULES["LOCATOR"] + " V59: retain the smallest COMPLETE source-native orientation relation for position, standing, path, movement, origin/destination, containment, accompaniment/carrying, support, proximity, recurrence/temporal position or figurative/internal orientation. A full movement/destination/standing expression may be the locator; do not shrink to a bare deictic if that loses relation identity. Exclude topical/content arguments and deictic/temporal words with no independent orientation job."
})
