"""Neutral V60 apparatus task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v58_task_rules import V58_BASE_RULES, V58_CLASS_RULES

V60_DELTA = """
V60 EXHAUSTIVE ROLE-LEDGER CORRECTION: preserve V58 anti-census discipline but supersede its rule that every primitive must be required by a selected material binding/frame. Read the entire source and reconstruct ALL represented research roles in source order, plus a separate scene/frame completion ledger. Primitive identity belongs only to an INDEPENDENT CLASS-NATIVE RESEARCH ROLE, not to every source-present or lexically separable phrase. Low-salience, background, nested, remembered, reported, recurring, prospective, questioned, negated, hypothetical and figurative roles qualify when they are genuine represented roles. For every candidate resolve one PRIMARY HOME before cross-class overlap. Cross-class reuse is exceptional and requires a second independent positive role that would otherwise disappear; grammar or shared wording is insufficient. Exhaustive coverage means every represented role/frame is checked, not that every noun, modifier, predicate, temporal expression, surface, path, prepositional phrase or descriptive fragment receives a unit. Run four checks before freeze: ROLE COVERAGE; SCENE/FRAME COMPLETION; PRIMARY-HOME/DUPLICATION; EXCESS. Scene/frame completion may add the smallest source-supported unnamed PLACE/TIME needed to preserve where/when represented relations occur, even when no selected binding previously required it. LABEL is a reusable represented value/state/classification role, not adjective/adverb census. VERB is an independent material lexical relation atom, not every grammatical/support/control predicate or an alternative decomposition of a LABEL/LOCATOR. LOCATOR is an independently reusable orientation relation, not every spatial/temporal/prepositional phrase. PLACE is an occurrence scene/position role, not every physical surface/component. TIME is a narrative/temporal frame organizing represented relations, not every event, duration, adverb or tense-marked phrase. OBJECT is a stable represented thing/content role, not every noun or clause complement. Freeze primitives before compounds. Emit one smallest complete compound per materially distinct represented binding; reject pairwise/combinatorial closure and alternative subset/superset decompositions. Preserve exact source vocabulary not only in source spans but also in researcher bundles; never normalize dialect, number or lexical choice. Never target hidden gold or expected counts.
"""

V60_BASE_RULES = V58_BASE_RULES + "\n" + V60_DELTA
V60_CLASS_RULES = dict(V58_CLASS_RULES)
V60_CLASS_RULES.update({
    "PLACE": V58_CLASS_RULES["PLACE"] + " V60 override: use exhaustive scene-completion after full-source role reconstruction. Retain each distinct source-supported physical occurrence scene/position needed to preserve where represented activity, interaction, participant position or independently represented object whereabouts occur, including minimal neutral unnamed/offscreen positions. Do not retain every floor/counter/wall/surface/path/component merely because it is physical; require an independent occurrence-position research role. PLACE/LOCATOR overlap requires two different positive roles.",
    "TIME": V58_CLASS_RULES["TIME"] + " V60 override: use exhaustive frame-completion after full-source role reconstruction. Retain distinct narrative/temporal episodes, periods, waits, phases, remembered/reported periods, recurring spans, present telling/reflection and prospective/future frames when they organize represented relations or distinguish periods. Do not turn every predicate, event mention, duration, frequency token, temporal adverb, hypothetical clause or discourse transition into TIME. Temporal wording whose substantive job is orientation belongs in LOCATOR unless a separate frame role exists.",
    "PERSON": V58_CLASS_RULES["PERSON"] + " V60: full-source actor coverage is mandatory. Retain each source-distinguished represented actor/group after coreference, including indirect, relational, possessive, offscreen, remembered and reported actors. Exclude generic, rhetorical, idiomatic or quoted second person when no stable represented actor role exists.",
    "OBJECT": V58_CLASS_RULES["OBJECT"] + " V60 override: retain independently represented stable things/content/choices/relations/sets/results/internal referents, including background concrete things when they actually participate as research roles. Reject incidental noun census, surfaces/components whose only job is scene description, clause/proposition wrappers, pronoun/deictic duplicates and analyst nominalizations. If wording chiefly expresses a value, relation or orientation, use its primary home instead of duplicating as OBJECT.",
    "LABEL": V58_CLASS_RULES["LABEL"] + " V60: LABEL is a reusable represented characterization/state/value/classification/polarity role. Preserve question, rejection, correction, comparison and uncertainty when intrinsic. Strongly reject ordinary scenic/descriptive modifiers, noun modifiers, intensifiers, manner adverbs and adjectives that merely describe a retained thing/event but do not become independent reusable value roles. Do not duplicate the same role as VERB solely because grammar uses a copula/state predicate.",
    "VERB": V58_CLASS_RULES["VERB"] + " V60: retain an independent material lexical relation atom only when it establishes a distinct represented binding among roles. Exclude auxiliaries, floor-management, stage mechanics, matrix/control/support predicates, locative/state copulas and syntactic subpredicates when their only substantive job is already represented by an embedded relation, LABEL or LOCATOR. Split matrix/embedded/coordinated relations only when each independently survives as a represented research relation. Avoid alternative lexical decompositions of one relation.",
    "LOCATOR": V58_CLASS_RULES["LOCATOR"] + " V60: retain only independently reusable orientation relations for position/path/direction/origin-destination/containment/support/accompaniment/proximity/temporal position/internal or figurative orientation. Do not census prepositional, deictic, temporal or spatial phrases. Reject ordinary arguments, topics, recipients, dates/durations and descriptive location phrases with no independent orientation job. A movement/standing expression may have LOCATOR as its primary home; do not redundantly duplicate it as VERB/TIME/PLACE unless each additional class has a separate positive role."
})
