"""Neutral V61 apparatus task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v58_task_rules import V58_BASE_RULES, V58_CLASS_RULES

V61_DELTA = """
V61 CLASS-PROJECTION CORRECTION: supersede any predecessor instruction requiring one exclusive primary semantic home or requiring a primitive to be necessary to a selected compound/binding. Read the entire source first and build an exhaustive represented-role ledger plus scene/frame coverage. Then project the source INDEPENDENTLY into each requested class. A source span may survive in more than one class when it independently performs each class's positive native function; cross-class semantic overlap is not itself duplication. Shared wording alone is insufficient, but no 'second different semantic role' is required. Remove overlap only when the candidate lacks a positive function in that class and exists merely because its words are parseable. Same-class aliases and alternative grains still collapse. PLACE/TIME require complete source-supported scene/frame coverage, including minimal neutral unnamed/offscreen positions, present-telling frames and explicit prospective/recurring frames when structurally distinguished. OBJECT includes stable background concrete things, source-reified choices/relations/categories/internal or figurative referents; reject analyst proposition wrappers. LABEL includes meaningful source-present characterizations, manner/state phrases, evaluations, comparisons, classifications, questioned/rejected/corrected labels and figurative qualities; it may overlap VERB/LOCATOR when each class test independently passes. VERB includes every material source-present lexical relation atom, including location/existence, action/movement, perception, cognition, reporting, waiting, state/change, modal/normative/prospective and embedded/matrix relations when each is a represented relation; exclude pure auxiliaries and discourse-only grammar. LOCATOR includes material source-native position/path/direction/destination/containment/support/accompaniment/recurrence/internal-orientation expressions and may overlap VERB/PLACE/TIME/LABEL when it independently functions as orientation. Preserve exact source wording/dialect/posture. Freeze primitives before compounds; reconstruct one smallest complete compound per materially distinct source-present binding using all and only materially co-bound frozen coordinates, including legitimate overlapping class projections. Never target hidden gold, expected counts, prior findings, or holdout material.
"""

V61_BASE_RULES = V58_BASE_RULES + "\n" + V61_DELTA
V61_CLASS_RULES = dict(V58_CLASS_RULES)
V61_CLASS_RULES.update({
    "PLACE": V58_CLASS_RULES["PLACE"] + " V61 override: perform generous scene completion. Retain each source-distinguished physical occurrence setting/position for represented actors, interactions and independently represented object whereabouts, including minimal neutral unnamed/offscreen positions when the source establishes an occurrence but not a location name, and a distinct present-telling place when the narrative distinguishes present telling. Do not exclude a valid PLACE because the same wording also supports LOCATOR/OBJECT.",
    "TIME": V58_CLASS_RULES["TIME"] + " V61 override: retain every source-distinguished revisit-able episode/period/frame: attempts, help episodes, transitions, waits, intended periods, remembered/reported periods, recurring spans, broad contextual periods, present reflection/telling and explicit prospective/future frames. Do not exclude TIME because related VERB/LOCATOR wording survives; exclude only mere tense/aspect tokens that do not establish a frame.",
    "PERSON": V58_CLASS_RULES["PERSON"] + " V61: full-source actor/group coverage after coreference is mandatory, including possessive, indirect, offscreen, remembered and reported actors. Exclude only generic/rhetorical/idiomatic humans that are not represented actors.",
    "OBJECT": V58_CLASS_RULES["OBJECT"] + " V61 override: retain complete stable-referent coverage, including background concrete things, components when independently referred to as things, named institutions/brands used as referents, internal/body referents, choices, decisions, relations, sets/categories, amounts/results, figurative objects and source-reified abstract content. Do not suppress OBJECT merely because LABEL/VERB/LOCATOR also represents related material. Reject pronoun/deictic duplicates and analyst-created proposition wrappers.",
    "LABEL": V58_CLASS_RULES["LABEL"] + " V61 override: retain meaningful source-present characterization/state/classification phrase grains, including descriptive qualities, manner-states, evaluations, comparisons, social/self labels, questioned candidate labels, immediate rejection/correction, polarity/status and figurative characterizations. LABEL may share wording with VERB or LOCATOR when it independently characterizes a represented role/state. Reject only descriptive material that has no meaningful represented characterization function.",
    "VERB": V58_CLASS_RULES["VERB"] + " V61 override: inventory all MATERIAL source-present lexical relation atoms, not only central actions. Include location/existence, movement, perception, possession, cognition/remembering/finding, speaking/reporting/asking/explaining, helping/attempting, waiting/standing/sitting, state/change, modal/normative/prospective and distinct matrix/embedded/coordinated relations. Preserve particles/complements/negation/modal material needed for relation identity. Do not suppress a material VERB merely because a LABEL or LOCATOR captures overlapping semantics. Exclude pure auxiliaries and discourse-only helpers.",
    "LOCATOR": V58_CLASS_RULES["LOCATOR"] + " V61 override: retain complete material source-native orientation relations for position, path, direction, origin/destination, entry/exit, containment, support/surface, accompaniment/carrying, standing/stuck/movement orientation, recurring/temporal context and figurative/internal orientation. Keep the smallest complete orientation expression, not just a bare preposition. LOCATOR may overlap VERB/PLACE/TIME/LABEL when it independently performs orientation. Reject only non-orienting arguments/topics/content."
})
