"""Neutral V62 apparatus task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v58_task_rules import V58_BASE_RULES, V58_CLASS_RULES

V62_DELTA = """
V62 BOUNDED-PROJECTION CORRECTION: preserve exhaustive represented-role/binding/frame coverage but do NOT convert every class-native parse into a primitive. Class-native function is necessary and NOT sufficient: every primitive must also be a coordinate-level represented role at lightweight research grain. Cross-class overlap remains legal, but only when each projection independently survives this full gate: source-supported represented role, positive class-native function, coordinate-level revisitability, lightweight distinction, no alternate decomposition, and no analyst wrapper. Use a counterfactual class test: if the overlapping projection were removed, would this candidate still be needed as an independently useful coordinate in this class? If not, remove it. Do not duplicate a characterization/state as OBJECT merely by nominalization or as LOCATOR merely because it contains orienting grammar; do not duplicate a copular/state predicate as VERB when LABEL completely carries the represented job; movement/action and orientation may coexist only when action and orientation are each independently material. Run symmetric COVERAGE + EXCESS checks for every class. Preserve genuine low-salience/background/offscreen roles, but reject lexical/descriptive/temporal/orientation census, generic narrator-place/time inference, support/matrix predicates without an independent binding, and alternate type assignments/decompositions. PLACE/TIME preserve source-distinguished scenes/frames only, not one per predicate. OBJECT requires stable source reification/content identity. LABEL requires a materially revisitable characterization/state/classification role, not adjective/adverb census. VERB requires a distinct represented lexical relation, not every predicate. LOCATOR requires orientation itself to be a material reusable relation, not every preposition/deictic/temporal attachment. Freeze primitives before compounds and emit only materially distinct binding compounds. Preserve exact source wording/dialect/posture. Never target hidden gold, expected counts, prior findings, or holdout material.
"""

V62_BASE_RULES = V58_BASE_RULES + "\n" + V62_DELTA
V62_CLASS_RULES = dict(V58_CLASS_RULES)
V62_CLASS_RULES.update({
    "PLACE": V58_CLASS_RULES["PLACE"] + " V62 override: preserve every SOURCE-DISTINGUISHED physical occurrence scene/position at lightweight grain, including minimal neutral unnamed/offscreen positions when a distinct interaction/actor position is physically established but unnamed. Do NOT infer a generic present-telling place merely because narration must happen somewhere, and do not turn surfaces, paths, destinations, supports, containers or object parts into PLACE unless they are independently revisitable occurrence positions.",
    "TIME": V58_CLASS_RULES["TIME"] + " V62 override: preserve SOURCE-DISTINGUISHED episode/period/frame coordinates that organize represented relations, including attempts, waits, transitions, remembered/reported periods, recurring periods and explicit prospective frames. Do NOT create TIME for every predicate, clause, tense/aspect token, duration, deictic or generic present telling. An unnamed TIME requires a materially distinguished frame, not mere occurrence.",
    "PERSON": V58_CLASS_RULES["PERSON"] + " V62: full actor/group coverage after coreference remains mandatory. Retain low-salience, possessive, relational, indirect, offscreen, remembered and reported actors when they are represented actors; reject classification words and generic/rhetorical humans that do not denote represented actors.",
    "OBJECT": V58_CLASS_RULES["OBJECT"] + " V62 override: retain concrete things when they have stable represented identity and materially participate in/recur across a binding, including low-salience background things. Retain abstract/content things only when the source itself reifies or revisits them as stable content. Reject clause/event/state wrappers, generic categories, every grammatical object, and alternate typing of LABEL/VERB/LOCATOR material that lacks independent thing/content identity.",
    "LABEL": V58_CLASS_RULES["LABEL"] + " V62 override: retain only materially revisitable source-present characterization/state/classification roles: meaningful conditions, evaluations, comparisons, self/social labels, questioned candidate labels, rejection/correction and polarity/status. Strongly reject ordinary adjectives, adverbs, manners, intensifiers, scenic descriptions and predicate fragments that do not become independent characterization coordinates. Orienting grammar inside a state phrase does not itself create LOCATOR, and a state does not itself create OBJECT.",
    "VERB": V58_CLASS_RULES["VERB"] + " V62 override: retain a lexical relation only when it independently establishes a represented binding job. Do not census every predicate. Exclude pure auxiliaries, floor-management/discourse scaffolding, stage mechanics, metacognitive/reporting/control helpers that only host another retained relation, and alternate subpredicate decompositions. A copular/state predicate needs no separate VERB when LABEL fully carries its represented job; keep VERB only if an independent material relation remains.",
    "LOCATOR": V58_CLASS_RULES["LOCATOR"] + " V62 override: retain orientation only when orientation itself is a materially represented reusable relation for position/path/direction/origin/destination/entry-exit/containment/support/accompaniment/proximity/temporal position or figurative/internal orientation. Reject every-preposition, deictic, duration, temporal-question, recipient, beneficiary, topic, content, instrument or grammatical-attachment census. A characterization/state phrase is not LOCATOR merely because it uses orienting grammar."
})
