"""Neutral V63 apparatus task rules. No gold rows/counts/evaluator findings/holdout content."""
from researcher_inventory.v58_task_rules import V58_BASE_RULES, V58_CLASS_RULES

V63_DELTA = """
V63 SCENE-BINDING CORRECTION: read the full source first and reconstruct a source-order ledger of represented people, stable things/content, qualities/states, material lexical relations, distinct physical scenes/positions, temporal/narrative episodes, material orientation relations, and cross-coordinate bindings. THEN project primitives by class. Primitive identity is a source-supported lightweight research ROLE OR BINDING SLOT, not a token census and not V62's requirement that each overlapping projection remain independently useful after another projection is removed. Preserve source-supported implicit scene/frame coordinates: when a distinct interaction, participant/object position, destination, episode, remembered/reported/prospective/reflection frame, or represented present-telling scene is established but unnamed, a neutral unnamed PLACE/TIME is legal and may be required. Present telling qualifies only when the telling itself is represented through current deictics, bodily/performance actions, explicit current reflection, or contrast with narrated scenes; do not infer it from narration alone. Cross-class overlap is legal when projections perform DIFFERENT binding jobs; reject overlap that is only grammatical recasting/nominalization. Run completeness BEFORE excess: first account for all scene/binding slots, then remove aliases, wrappers, support grammar, token-level descriptions, redundant alternate grains, and duplicate decompositions. Do NOT exclude a relation merely because it is embodied/stage/performance, reporting, cognitive, copular, or embedded; keep it when it supplies a distinct represented binding. OBJECT may include stable concrete referents and stable abstract choice/relation/internal/content slots even without explicit nominal reification, but reject discourse/clause/event wrappers whose only job is to point back to an already represented binding. LABEL may include a materially qualifying manner as well as quality/state/evaluation/classification when removing it would erase source-present characterization; do not adjective/adverb-census. LOCATOR may overlap PLACE/TIME/LABEL/VERB when it carries a distinct orientation job; preserve source-native deictic/path/temporal/situational/figurative orientation but do not preposition-census. Freeze primitives, then reconstruct one smallest materially complete compound per distinct binding, using all and only frozen coordinates materially co-bound there; do not attach every scene-wide coordinate to every clause or emit alternate subset/superset decompositions. Preserve exact wording/dialect/posture. Never target hidden gold, expected counts, prior findings, or holdout material.
"""

V63_BASE_RULES = V58_BASE_RULES + "\n" + V63_DELTA
V63_CLASS_RULES = dict(V58_CLASS_RULES)
V63_CLASS_RULES.update({
    "PLACE": V58_CLASS_RULES["PLACE"] + " V63 override: reconstruct physical SCENE/POSITION slots, not physical-noun tokens. Retain named settings and source-supported unnamed positions for distinct interactions, participant/object whereabouts, destinations/offscreen positions, or embodied scenes. Larger setting plus contained position may both survive when source structure distinguishes both. A represented present-telling scene may have an unnamed PLACE under the V63 deictic/embodiment/reflection gate.",
    "TIME": V58_CLASS_RULES["TIME"] + " V63 override: reconstruct EPISODE/PERIOD slots that organize bindings. Retain named or unnamed frames for distinct attempts/interactions/waits/transitions, remembered/reported events, recurring or intended/prospective periods, reflection episodes, and represented present telling. Do not make one TIME per predicate or temporal token; several relations may share one frame.",
    "PERSON": V58_CLASS_RULES["PERSON"] + " V63: full represented actor/group coverage after coreference. Keep indirect/possessive/relational/offscreen/reported/prospective actors; reject generic/rhetorical addressees and classification words that do not denote represented actors.",
    "OBJECT": V58_CLASS_RULES["OBJECT"] + " V63 override: retain stable concrete things that materially participate/are located/acted-on/described and stable abstract choice/relation/decision/internal/figurative/content slots that function as arguments in bindings. Explicit nominal reification is not required when stable content identity is source-supported. Reject discourse wrappers, whole-clause/event wrappers, generic summary nouns, pronoun duplicates, and nominalizations whose research job is already carried by binding constituents.",
    "LABEL": V58_CLASS_RULES["LABEL"] + " V63 override: retain source-present quality/state/evaluation/comparison/classification/correction/polarity AND materially qualifying manner when it characterizes a retained coordinate or relation at lightweight grain. Preserve question/negation/uncertainty/intensity/idiom. Do not adjective/adverb census; collapse redundant restatements of the same characterization.",
    "VERB": V58_CLASS_RULES["VERB"] + " V63 override: retain every materially distinct source-present lexical relation that supplies a binding job, including embodied/performance actions, cognition/reporting, copular/state, and embedded relations when material. Exclude auxiliaries/discourse-floor/support predicates only when removing them preserves the full represented relation and posture. Split serial/matrix/embedded predicates only when each has a distinct binding role.",
    "LOCATOR": V58_CLASS_RULES["LOCATOR"] + " V63 override: retain material source-native orientation jobs for position/path/direction/origin/destination/entry-exit/containment/support/accompaniment/proximity, temporal/recurring position, situational, figurative or internal orientation. Overlap with PLACE/TIME/LABEL/VERB is legal when orientation is a distinct binding slot. Do not preposition/recipient/topic/instrument/duration census."
})
