"""Neutral V64 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V64_BASE_RULES = """
V64 BOUNDED-GRAIN RULE: read the entire source and first reconstruct (a) represented physical scenes/positions, (b) temporal episodes/periods, (c) represented actors, stable referents/content, source-present characterizations, lexical relations, material orientation edges, and materially distinct bindings. SCENE/FRAME COMPLETION and PRIMITIVE ADMISSION are separate. Use PLACE/TIME to preserve source-supported scene/frame containers, including unnamed anchors for genuinely distinct interactions/relationship episodes/offscreen positions/remembered or prospective frames; do not turn every physical noun, surface, path, deictic, duration, aspect word, transition, or predicate-local moment into PLACE/TIME. For all classes compress to one smallest source-native coordinate per distinct lightweight research job. Explicit/parseable wording is not enough. Reject clause/event wrappers, support predicates, nominalization echoes, property-predicate duplicates, component/surface places, temporal/deictic fragments, preposition census, alternate grains, and duplicate decompositions. Cross-class overlap is legal only when the two projections perform genuinely different schema jobs, not merely different grammatical parses. Preserve exact wording, dialect, punctuation, polarity, modality, question, uncertainty, comparison, attribution and correction. Q means source qualities are available; it does not force every quality to become LABEL. Freeze primitives before compounds. Emit one smallest materially complete compound per distinct source-present binding/classification/orientation, with all and only frozen coordinates materially co-bound there; do not emit pairwise closure, every primitive as its own compound, broad scene supersets, or alternate subset/superset decompositions. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V64_CLASS_RULES = {
    "PLACE": "PLACE = physical occurrence setting/position at scene grain. Keep named settings and source-supported unnamed positions when a distinct interaction, relationship episode, participant/object whereabouts, offscreen destination, remembered/reported scene, or embodied present scene needs a physical anchor. Do not promote every floor/counter/wall/side/container/support/vehicle/object/path to PLACE; those remain OBJECT/LOCATOR unless their physical position itself is a distinct occurrence setting.",
    "TIME": "TIME = episode, period, phase, or frame organizing one or more represented bindings. Keep distinct attempts/interactions/waits, remembered/reported episodes, recurring/relationship spans, intended/prospective periods, reflective frames, and represented present telling when source structure distinguishes them. Do not create TIME from every now/still/always/then/date/duration/frequency/aspect/deictic or predicate-local temporal word; several relations may share one frame.",
    "PERSON": "PERSON = every source-distinguished represented human/social actor or stable group after coreference, including indirect/possessive/relational/offscreen/reported/prospective actors. Keep speaker as B. Exclude generic/rhetorical addressees and classification words that do not denote actors.",
    "OBJECT": "OBJECT = stable concrete thing or stable abstract/content referent used as an argument/revisitable coordinate. Keep concrete participating/referred things and stable choices/decisions/relations/internal or figurative content when source-treated as a referent. Use one object per referential identity. Reject nested clause/proposition wrappers, generic what-happened/what-wanted wrappers, event nouns, pronoun duplicates and nominalizations whose content is already carried by a relation plus arguments.",
    "LABEL": "LABEL = source-present characterization whose value itself is research-useful: quality/state/evaluation/comparison/classification/self-or-other label/correction/rejection/polarity/status/material manner. Prefer the value phrase rather than duplicating its support/copular predicate. Preserve question/negation/uncertainty/intensity/idiom. Do not adjective/adverb census or promote whole questions/reactions merely because they contain evaluative wording.",
    "VERB": "VERB = smallest complete lexical relation for a materially represented binding. Keep material action/movement/perception/possession/cognition/reporting/asking/helping/causing/attempting/waiting/posture/change/performance relations. Compress matrix+embedded, serial, coordinated, phrasal and support grammar into one VERB when splitting only reproduces syntax; split only when each relation independently changes or participates in a distinct binding. Do not emit pure auxiliaries, copular/property carriers, LABEL restatements, LOCATOR restatements, discourse-floor mechanics or duplicate support predicates.",
    "LOCATOR": "LOCATOR = smallest source-native orientation edge materially positioning a retained coordinate/binding: position/path/direction/origin/destination/entry-exit/containment/support/accompaniment/proximity-distance/recurrence-context/figurative or internal orientation. Do not preposition, recipient, topic, instrument, duration, frequency, deictic or temporal-token census. Bare temporal wording normally locates a TIME frame rather than creating another LOCATOR unless orientation itself is a distinct research job."
}
