"""Neutral V65 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V65_BASE_RULES = """
V65 INDEPENDENT-PROJECTION RULE: read the entire source and reconstruct the represented people/groups, stable referents/content, characterizations/states, lexical relations, physical settings/positions, temporal episodes/periods, orientation/context edges, and source-local bindings. Lightweight means source-grounded and non-interpretive; it does NOT mean force one source span into only one schema class. Evaluate each requested class independently. Cross-class overlap is legal when the same source wording performs different class-specific jobs; do not choose one exclusive primary home and erase the others. Within a class, merge aliases/coreference and reject same-job alternate decompositions. Preserve exact wording, dialect, punctuation, polarity, modality, question, uncertainty, comparison, attribution, correction, recurrence and prospective posture. For PLACE/TIME retain supported unnamed anchors when distinct represented scenes/episodes require them. Freeze primitives before compounds. Build one smallest materially complete compound per source-local binding; do not fuse neighboring predicates into thematic/scene bundles, and do not emit pairwise closure or alternate subset/superset variants. Include all and only frozen class projections materially co-bound in that binding. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V65_CLASS_RULES = {
    "PLACE": "PLACE = source-supported physical setting or position used to locate represented material. Keep named settings, contained/interaction/waiting positions, participant or object whereabouts, destinations, remembered/reported settings, figurative physical scenes presented as scenes, and supported unnamed anchors for distinct occurrences. A vehicle/container/surface/body of water/structure or other concrete referent may be PLACE when source use makes it the physical setting or position; being object-like does not exclude the PLACE projection. Reject decorative physical nouns and unsupported inferred places.",
    "TIME": "TIME = source-distinguished episode, period, phase, attempt, wait, transition, intended/prospective period, recurring span, remembered/reported episode, reflective episode, or future/possible frame. A TIME need not have clock wording. Distinct action phases may be distinct TIME coordinates within one broad scene. Do not create TIME for every tense/aspect/deictic token when no distinct represented frame exists.",
    "PERSON": "PERSON = speaker B plus every source-distinguished represented human/social actor or stable group after coreference, including indirect/possessive/relational/offscreen/reported/quoted/prospective actors when part of represented material. Exclude generic rhetorical addressees and words that are only classifications.",
    "OBJECT": "OBJECT = stable concrete thing or stable abstract/content referent independently revisitable in represented material. Keep concrete participants, amounts/results/services, choices, decisions, relations, propositions/content, internal or figurative referents when source-treated as stable things. Being eligible for another class does not automatically exclude OBJECT. Reject unsupported clause wrappers, pronoun duplicates and nominalizations that add no independent referential identity.",
    "LABEL": "LABEL = source-present characterization, quality, state, evaluation, comparison, identity, self/other label, status/polarity, materially qualifying manner, correction/rejection or classification. Preserve the complete source-native value and posture. LABEL may overlap VERB/LOCATOR/TIME when characterization is an independent schema job; do not suppress it merely because grammar is predicative, positional, deictic or embedded. Reject ordinary modifiers with no independently revisitable characterization job.",
    "VERB": "VERB = source-present lexical relation or predicate construction materially connecting or positioning retained coordinates. Keep actions, movement, perception, cognition, reporting, asking, helping, attempting, waiting/posture, possession, change, positional relations, modal/prospective relations, and support/copular constructions when the relation itself carries a distinct binding. Compress only true single lexical constructions or same-job grammatical fragments; split when relations independently participate in different bindings. Preserve negation/modality/question/particles/required complements.",
    "LOCATOR": "LOCATOR = smallest complete source-native orientation/context edge materially locating a coordinate or binding: setting relation, contained position, path/direction, origin/destination, entry/exit, accompaniment, proximity/distance, support/containment, embodied/deictic position, recurrence/context orientation, internal/figurative orientation, or movement-to-destination construction. Do not preposition-census. LOCATOR may overlap PLACE/TIME/LABEL/VERB when orientation itself is independently represented."
}
