"""Neutral V66 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V66_BASE_RULES = """
V66 BOUNDED-INDEPENDENT-PROJECTION RULE: read the whole source first. Independently evaluate every requested schema class, but cross-class overlap is permission only AFTER each proposed primitive independently passes bounded class admission. A span being parseable or already useful in another class neither excludes nor admits a new projection. First reconstruct a small source-order scene/frame ledger: one minimal PLACE/TIME anchor for each materially distinct represented physical setting/position or temporal episode/period/relationship/prospective/present-reflective frame that organizes bindings; supported unnamed PLACE/TIME anchors are allowed. Do not create PLACE/TIME for every movement, predicate, tense, deictic, duration, destination token or local action. For every primitive require: exact source support; a materially useful class-specific job; stable same-class distinctness; and smallest complete source-native grain. Reject aliases, clause wrappers, support grammar, property-predicate duplicates, token/preposition census and alternate decompositions. OBJECT preserves stable concrete referents and source-treated stable choices/options/decisions/relations/content, but not one-off clause wrappers. LABEL keeps characterization values, not full predicate/support clauses. VERB keeps the smallest exact lexical relation; arguments/embedded content normally belong in compounds, while matrix perception/cognition/reporting and embedded predicates may both survive only when each independently binds coordinates. LOCATOR keeps only material orientation edges. Before return, every non-null source_wording/source_cue/order_cue must be an exact contiguous source substring; never paraphrase or normalize. Freeze primitives before compounds. Emit one smallest materially complete compound per distinct source-local binding with all and only materially co-bound frozen coordinates. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V66_CLASS_RULES = {
    "PLACE": "PLACE = physical occurrence setting/position at scene grain. Keep named settings and source-supported unnamed anchors for materially distinct interactions, waits, relationship episodes, participant/object whereabouts, remembered/reported scenes, prospective positions or present represented settings when physical position organizes the material. A concrete referent may also be OBJECT if thing-identity and setting-position are independently useful. Do not promote every surface/container/path/movement endpoint/object/deictic into PLACE; a destination phrase counts only when the destination/position itself is a distinct represented coordinate.",
    "TIME": "TIME = episode, period, phase, relationship span, wait, remembered/reported event, recurring frame, intended/prospective period or represented present frame organizing one or more bindings. Several relations may share one TIME. Do not create TIME from every action, predicate, tense/aspect form, now/then/still/date/property/question/transition or predicate-local moment unless the source independently establishes a distinct frame.",
    "PERSON": "PERSON = speaker B plus every source-distinguished represented human/social actor or stable group after coreference, including indirect/possessive/relational/offscreen/reported/quoted/prospective actors when part of represented material. Exclude generic rhetorical addressees and classification words that do not denote actors.",
    "OBJECT": "OBJECT = stable concrete thing or stable abstract/content referent independently revisitable as an argument/research coordinate. Keep source-treated stable amounts, choices/options, decisions, relations, propositions/content, services/results and internal/figurative referents when their identity is independently present. Reject pronoun duplicates, generic clause wrappers, one-off event restatements, nested proposition copies and nominalizations that merely rename a binding already carried by a relation plus arguments.",
    "LABEL": "LABEL = smallest complete source-present characterization value that is independently useful: quality/state/evaluation/comparison/identity/classification/correction/rejection/polarity/status/material manner. Preserve question/negation/uncertainty/intensity/idiom when part of the value. Do not promote full predicate/support clauses, ordinary modifiers, discourse reactions, temporal/deictic wording or every verbal state into LABEL.",
    "VERB": "VERB = smallest complete exact source-present lexical relation materially binding retained coordinates. Arguments and embedded content normally belong in the compound, not inside VERB wording. Keep only particles/negation/modality/complements required for relation identity. Matrix perception/cognition/reporting may survive when it independently binds actor to content; embedded predicates may separately survive when they independently bind coordinates. Do not split auxiliaries/support grammar/property carriers into extra verbs. Never paraphrase source_wording.",
    "LOCATOR": "LOCATOR = smallest source-native orientation edge materially positioning a retained coordinate/binding: physical position/path/direction/origin/destination/entry-exit/containment/support/accompaniment/proximity-distance/recurrence-context/embodied or internal/figurative orientation. Do not preposition, recipient, topic, instrument, duration, frequency, discourse-marker, deictic or temporal-token census; ordinary complements stay in the binding unless orientation itself is a distinct research job."
}
