"""Neutral V67 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V67_BASE_RULES = """
V67 SOURCE-COORDINATE RULE: read the whole source first and inventory researcher-useful source coordinates, not a minimal semantic graph and not a grammar census. Type by the research job the source-present wording performs, never by part of speech alone. A source span may project into more than one class when each projection has an independently useful class job; overlap is allowed without forcing overlap. Preserve analytically distinct PLACE/TIME coordinates when the source establishes distinct scene positions, interaction/wait/reporting/prospective frames, even when they share the same broad physical setting or chronology. Do not create PLACE/TIME from mere descriptive tokens, tense, duration, movement, or syntax. OBJECT keeps source-distinguished concrete or stable abstract/figurative referents after coreference; deduplicate aliases and wrappers. LABEL keeps the smallest complete characterization value, including verbal/stative/idiomatic/questioned/negated wording when the source uses that wording as a characterization. VERB keeps the smallest complete source-native relation packet rather than atomizing to a single lexical head: preserve auxiliaries, negation, particles, coordinated action, stance, or complements when they are part of the relation's source identity; do not separately emit embedded/support verbs unless each relation binds coordinates independently. LOCATOR keeps the smallest complete source-native orientation/context relation, including physical, contextual, recurring, internal, figurative, path, destination, or position wording when orientation itself is useful; do not census prepositions or temporal tokens. Every non-null source_wording/source_cue/order_cue must be an exact contiguous source substring. Freeze primitives before compounds. Compounds are proposition-level researcher bindings: create one materially complete bundle for a distinct source-local proposition/attribution/question/position/comparison, merge co-bound relation/value/orientation coordinates into that bundle, and do not emit nested partials, pairwise closure, alternate decompositions, or a compound merely because a primitive exists. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V67_CLASS_RULES = {
    "PLACE": "PLACE = physical setting or position that is independently useful for a represented scene/binding. Preserve distinct unnamed positions or scene anchors when the source distinguishes a participant/object location, interaction, wait, reported/remembered scene, prospective position, or present-telling setting even if it is co-located with a broader named place. Merge true aliases; do not collapse merely because two PLACE coordinates occur in the same broad location. Reject figurative-only wording, descriptive nouns, and movement endpoints that do not establish a physical coordinate.",
    "TIME": "TIME = source-distinguished episode, period, wait, interaction phase, relationship span, remembered/reported frame, recurring span, intended/prospective period, or present-telling/reflection frame. Nested or adjacent TIME coordinates may both survive when each organizes different material. Do not reduce everything to one scene-wide frame, and do not create TIME from every tense, duration token, adverb, predicate, or local moment.",
    "PERSON": "PERSON = speaker B plus every source-distinguished represented human/social actor or stable group after coreference, including indirect, possessive, offscreen, remembered, reported, prospective, and comparison actors when represented. Resolve true aliases/coreference; exclude generic rhetorical addressees and mere classification words.",
    "OBJECT": "OBJECT = source-distinguished concrete thing or stable abstract/content/figurative referent that can be revisited as an argument or research coordinate. Preserve choices, decisions, relations, feelings/content, internal referents, figurative things and propositions when the source treats them as identifiable things. Merge aliases/coreference and avoid duplicate surface mentions. Reject one-off clause wrappers, grammatical complements, event restatements, and nominalizations that add no stable referent.",
    "LABEL": "LABEL = smallest complete source-present characterization value: quality, state, evaluation, comparison, identity/classification, correction/rejection, polarity/status, or materially qualifying manner. Type by characterization function rather than grammar: participles, verbal/stative phrases, idioms, questions, negations and corrections may be LABEL when the value itself is the coordinate. Preserve the whole smallest source-native value needed for its posture; reject incidental modifiers and discourse filler.",
    "VERB": "VERB = smallest complete exact source-native relation packet materially binding coordinates. Do not mechanically shrink to one lexical head. Preserve multiword attempts, reports, cognition, stance, negation, particles, coordinated action, relation complements, waiting/posture, modal/prospective or positional wording when needed to identify the relation as expressed. Do not split auxiliary/support syntax or emit nested verbs merely because they are parseable. A matrix and embedded relation may both survive only when each independently binds coordinates. Never paraphrase source_wording.",
    "LOCATOR": "LOCATOR = smallest complete source-native orientation/context coordinate that materially locates a retained entity or binding: physical position/path/direction/origin/destination, containment/support, accompaniment, recurrence-context, internal/figurative orientation, or another source-present locating relation. The useful locator may be a phrase rather than a preposition and may overlap LABEL/VERB when it independently performs orientation. Reject preposition, recipient, topic, instrument, duration, frequency, or temporal-token census when no orientation job exists."
}
