"""Neutral V68 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V68_BASE_RULES = """
V68 ARCHETYPAL-COORDINATE ECONOMY RULE: read the whole source first. Build a sparse but complete inventory of durable research lookup coordinates, not a grammar census and not a minimal semantic graph. Source presence is necessary but not sufficient: a primitive survives only when it has an independently useful class-specific research job that should remain available outside the single proposition where it appears. Type by that job, not part of speech. First reconstruct a source-order scene/frame ledger at episode grain: retain materially distinct represented settings/participant-position scenes and temporal episodes/relationship/prospective/present-reflective frames, including supported unnamed anchors, but do not turn surfaces, containers, paths, action phases, predicate-local moments, adverbs or durations into separate PLACE/TIME merely because they are mentioned. Then admit selected PERSON/OBJECT/LABEL/VERB/LOCATOR coordinates at the smallest complete exact source-native grain. OBJECT is a stable revisitable thing/referent, not a noun/content census. LABEL is an independently reusable characterization value, not every modifier/evaluation. VERB is a sparse exact relation atom needed to bind research coordinates; arguments and ordinary complements belong in compounds, and support/matrix/auxiliary wording is excluded unless it independently expresses a retained relation. LOCATOR is a selected orientation/context atom, not a prepositional census. Cross-class duplication is exceptional: allow it only when the same source span performs two independently necessary durable jobs. Every non-null source_wording/source_cue/order_cue must be a character-for-character contiguous source substring; never normalize dialect, number, wording or punctuation. Freeze primitives before compounds. Emit one smallest materially complete source-local semantic binding per distinct research relation/attribution/question/position/comparison, using only frozen coordinates and the material scene/frame anchors; do not emit prose wrappers, clause-by-clause inflation, pairwise closure, alternate decompositions or scene-wide supersets. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V68_CLASS_RULES = {
    "PLACE": "PLACE = durable physical scene/participant-position setting at episode grain. Keep named settings and supported unnamed anchors when a materially distinct represented interaction, participant/object whereabouts, remembered/reported scene, prospective position or present represented setting needs its own scene coordinate. Do not promote every surface, container, body part, object-support relation, path segment, movement endpoint or micro-position into PLACE; those normally remain object/orientation/binding detail unless the source establishes a distinct scene axis.",
    "TIME": "TIME = durable episode/frame coordinate organizing represented material: event period, relationship span, remembered/reported episode, recurring frame, intended/prospective period or represented present-telling/reflection frame. Several relations may share one TIME. Do not create TIME for every action phase, predicate, wait fragment, local duration, tense/aspect form, adverb, transition or predicate-local moment unless it independently establishes a materially distinct episode axis.",
    "PERSON": "PERSON = speaker B plus every source-distinguished represented human/social actor or stable group after coreference, including indirect, possessive, relational, offscreen, remembered, reported, prospective and comparison actors when represented. Resolve true aliases/coreference; exclude generic rhetorical addressees and classification words that do not denote actors.",
    "OBJECT": "OBJECT = selected stable concrete thing or stable abstract/content referent independently revisitable across research bindings. Keep source-distinguished things, stable choices/options/decisions/relations/content/internal or figurative referents when they have thing-like identity. Reject pronoun duplicates, generic nouns, one-off clause contents, local event restatements, feelings/evaluations that function only as LABEL, parseable complements and nominalizations whose only job is already carried by a binding.",
    "LABEL": "LABEL = smallest complete exact source-present characterization value independently reusable as a research coordinate: quality/state/evaluation/comparison/identity/classification/correction/rejection/polarity/status/material manner. Preserve source-native uncertainty, question, negation, intensity and correction where part of the value. Do not census adjectives, descriptive tokens, discourse reactions, full predicate clauses or evaluations whose only research role is local to one binding.",
    "VERB": "VERB = sparse smallest complete exact source-native lexical relation atom materially required to bind retained coordinates. Keep main event/relation atoms and independently binding coordinated or embedded relations. Arguments and ordinary complements stay outside the VERB and are linked by compounds. Exclude auxiliaries, support verbs, stance/reporting/cognition wrappers, property carriers and matrix packaging when their only job is to introduce another retained content relation. Keep particles/negation/complements inside VERB only when lexically inseparable from the relation identity. Never paraphrase or normalize source_wording.",
    "LOCATOR": "LOCATOR = selected exact source-native orientation/context atom that independently positions a retained coordinate or binding: material position/path/direction/origin/destination/containment/support/accompaniment/proximity, recurring-context or embodied/internal/figurative orientation. A multiword phrase is allowed when the whole phrase is the orientation coordinate. Do not census prepositions, recipients, topics, instruments, durations, frequency phrases, discourse markers, physical micro-sublocations or temporal wording when no independent orientation job exists.",
}
