"""Neutral V69 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V69_BASE_RULES = """
V69 SOURCE-DISTINCTION COVERAGE RULE: read the entire source before extraction. Produce a bounded semantic coordinate inventory, not an exhaustive grammar census and not a minimal semantic graph. A primitive survives when it is source-supported, carries a distinct class-specific lookup/binding job, preserves a represented distinction that would otherwise disappear, and is not merely an alias, duplicate mention, auxiliary-only fragment, or mechanical token. Recurrence and usefulness outside the original proposition are NOT required; a single-use source-distinguished event, relation, orientation, characterization, choice/content target, or frame may be necessary. Type by semantic job, not part of speech. First make a source-order coverage pass, then compress only true duplicates and mechanical grammar. Preserve materially distinct subepisodes within a broader scene; stable concrete and abstract targets/options/relations/situations/content; complete characterization posture; complete source-native relation identities including cognition/stance/report/location/intention; and complete physical or figurative orientation relations. Cross-class overlap is allowed whenever the same exact source span performs different real class jobs; do not delete a valid projection merely to avoid overlap. Every non-null source_wording/source_cue/order_cue must be a character-for-character contiguous source substring. Freeze primitives after coverage/compression. Then create one maximally complete local compound per source-distinguished proposition/attribution/question/position/comparison/decision/intention/event relation, containing all retained coordinates materially co-bound there, including relevant frame anchors. Do not emit nested partials, pairwise subsets, alternate decompositions, duplicate bundles, or scene-wide supersets. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V69_CLASS_RULES = {
    "PLACE": "PLACE = source-distinguished physical or represented setting/scene anchor. Keep named or supported unnamed settings for distinct interaction, remembered/reported, participant/object whereabouts, comparison, prospective, or current scenes. Co-located/nested settings may both survive when their scene jobs differ. Reject only mechanical surfaces/edges/path points that are mere orientation detail rather than distinct represented settings.",
    "TIME": "TIME = source-distinguished temporal/event frame, including materially distinct subepisodes inside one broader scene. Keep attempts, interventions/help episodes, departures/waits/returns or event-state changes, intended/counterfactual periods, remembered/reported episodes, recurring frames, prospective similar situations, and present reflection when they organize distinct material. Do not mint TIME for every verb/tense/adverb when no separate event/frame distinction exists.",
    "PERSON": "PERSON = speaker B plus every source-distinguished represented human/social actor or stable group after coreference, including indirect, possessive, relational, offscreen, remembered, reported, prospective, and comparison actors. Resolve true aliases; exclude only generic rhetorical addressees/non-actors.",
    "OBJECT": "OBJECT = source-distinguished concrete thing or stable abstract/content target that can be referred to, chosen, related to, evaluated, remembered, decided, or acted upon. Keep choices/options, decisions, relations, situations, plans, represented content, internal/figurative targets, and other thing-like referents even if single-use. Reject true coreference duplicates, nonreferential generic nouns, and grammar-only complements with no distinct target job.",
    "LABEL": "LABEL = exact source-present characterization value: quality, state, evaluation, comparison, identity/classification, correction/rejection, polarity/status, experiential/epistemic description, or material manner. Preserve the smallest complete source-native span carrying the full posture; verbal, clausal, idiomatic, or locative-looking wording may be LABEL when characterization is its job. Preserve uncertainty, negation, question, intensity, correction, contrast, and attribution.",
    "VERB": "VERB = exact source-native relation/predicate coordinate. Keep source-distinguished action, perception, cognition, stance, speech/report, possession, location, intention, evaluation, change, causation, comparison, waiting/continuation, and other represented relations. Use the smallest semantically COMPLETE source span: keep particles/infinitival material/complements/negation when removing them changes the relation identity. Do not reject cognition/report/stance/copular/location relations merely as wrappers. Exclude auxiliary-only morphology and duplicate relation mentions.",
    "LOCATOR": "LOCATOR = exact source-native orientation/context relation positioning a person/object/event/relation: position, containment, proximity, path, direction, origin/destination, approach/departure, arrival/exit, accompaniment, recurring context, embodied/internal, or figurative orientation. Movement/state phrases may overlap VERB or LABEL when orientation is a separate job. Use the smallest semantically complete locating span; reject only incidental or duplicate context with no orientation distinction.",
}
