"""Neutral V70 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V70_BASE_RULES = """
V70 ARCHETYPAL LIGHTWEIGHT RULE: read the whole source before extracting the requested class. Preserve materially represented coordinates that are independently selectable for later research lookup/binding; do not perform a token, grammar, clause, or technically-possible cross-class census. Single-use is allowed when the item has its own coordinate identity; local grammatical fragments, whole-proposition restatements, argument phrases, and duplicate projections do not become primitives merely because they can be named. Reconstruct materially distinct scene/frame anchors first, including supported unnamed PLACE/TIME anchors when a material object/participant location, destination, waiting scene, later interaction, present telling/reflection, recurring frame, or prospective frame needs its own coordinate. Several relations may share one TIME. Type by semantic research job. Cross-class overlap is permitted only when each projection contributes a separately addressable class-specific coordinate; do not duplicate a motion/state phrase into LOCATOR merely because it looks directional if its only job is the predicate. Preserve exact source language with no synonym substitution, normalization, dialect repair, number change, or invented wording. Freeze primitives only after an independent-selectability/type audit. Then create one materially complete local compound per distinct source binding using all and only frozen coordinates actually co-bound there; no pairwise subsets, alternate decompositions, duplicate bundles, or scene-wide supersets. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V70_CLASS_RULES = {
    "PLACE": "PLACE = materially distinct physical or represented setting/scene coordinate. Keep explicit broad and contained settings when both organize represented material. Keep supported unnamed places for a material object location, destination, waiting position, later interaction/conversation, remembered/prospective scene, participant-position scene, or present telling when the place is unnamed but the scene coordinate is real. Reject surfaces, body parts, container edges, support points, path points, movement endpoints, and spatial-looking phrases that are only orientation detail rather than a distinct setting. Do not duplicate a thing as PLACE when its only job is OBJECT.",
    "TIME": "TIME = materially distinct temporal/event frame in source progression. Keep staged attempts/conditions, help/response episodes, departures/transitions, waits, intended periods, later conversations/reports, remembered episodes, recurring spans, present reflection/telling, and prospective/future frames when they organize distinct material. Several relations may share one TIME. Do not mint TIME for every predicate, subaction, question, local phase, tense/aspect form, duration, adverb, or clause.",
    "PERSON": "PERSON = speaker B plus every materially represented human/social actor or stable group after coreference, including indirect, possessive, relational, offscreen, remembered, reported, prospective, and comparison actors when represented. Resolve true aliases/coreference; exclude generic rhetorical addressees and classification words that do not denote actors.",
    "OBJECT": "OBJECT = materially represented independently selectable concrete or abstract thing. Keep source-distinguished wholes/parts, amounts/values, orders/services/results, decisions/next steps, contemplated choices treated as things, stable relations/situations/plans, named sets/categories, and internal/figurative represented objects. Do not perform a noun/proposition census: reject whole assertions/questions, reason clauses, event restatements already carried by TIME/VERB plus arguments, transient argument phrases, and referents whose only job is PLACE. Single-use objects may survive when they have independent thing-like identity.",
    "LABEL": "LABEL = independently selectable exact source-present characterization value: quality, state, evaluation, comparison, identity/classification, correction/rejection, polarity/status, experiential/epistemic description, or material manner. Use the shortest complete source-native value carrying the posture. Preserve uncertainty, question, negation, intensity, correction, contrast, and idiom when part of that value. Do not emit an entire proposition, question sentence, reason clause, or predicate packet when a smaller source-present characterization carries the LABEL job.",
    "VERB": "VERB = materially represented lexical relation/predicate increment. Keep principal relations and coordinated/embedded relations when each has its own represented relational job. Retain cognition, stance, report, recall, perception, intention, comparison, location, waiting/continuation, and matrix relations when they materially add epistemic/attributional/modal or relational posture; do not discard them merely because an embedded relation also exists. Use the smallest semantically complete exact source-native lexical construction; keep particles, negation, reflexives, or required complements only when removing them changes relation identity. Ordinary subjects/objects/recipients/topics/optional complements belong in compounds. Reject auxiliaries, support packaging, and every-parseable-subpredicate inflation.",
    "LOCATOR": "LOCATOR = selected exact source-native orientation/context relation independently positioning a retained person/object/event/relation. Keep material physical or figurative position, containment, support, proximity, path, direction, origin/destination, accompaniment, recurring-context, or embodied/internal orientation when orientation itself is independently selectable. Use the smallest complete meaningful construction, not an isolated preposition. Do not classify a phrase as LOCATOR merely because it contains motion/directional-looking language; if its only job is the predicate, keep VERB only. Reject recipients, topics, instruments, durations, frequency fragments, discourse/causal phrases, and generic complements without an independent orientation job.",
}
