"""Neutral V71 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V71_BASE_RULES = """
V71 ARCHETYPAL LIGHTWEIGHT RULE: read the whole source before extracting. Build the scene ledger first, then lexical classes. Admit a primitive only when it has exact source support (or a supported unnamed PLACE/TIME), a genuine class-specific research job, independent selectability, and no redundant alias/restatement/projection. Single-use is allowed; grammar, clausehood, salience, technical parseability, and the ability to paraphrase do not create a coordinate. PLACE is a scene/occurrence-position, not any spatial phrase; preserve supported unnamed participant/object locations, destinations, waiting scenes, later conversation scenes, remembered/prospective scenes, and present-telling scenes when materially distinct. TIME is a scene-level episode/frame, not every predicate, question, contemplated action, subphase, duration, or adverb; several relations normally share a frame. Type by represented research job before considering overlap: scene->PLACE, frame->TIME, actor->PERSON, thing/relation-as-thing->OBJECT, characterization/state/value->LABEL, lexical relation->VERB, orientation/path/context->LOCATOR. Cross-class overlap is conservative and survives only when each projection independently contributes a different class job. Preserve exact source language with no synonym substitution, normalization, dialect repair, spelling cleanup, number change, or invented wording. Freeze primitives before compounds. Then scan every retained relation-bearing VERB/LABEL/LOCATOR and create one materially complete local compound for its binding (or one inseparable coordinated relation), including all and only frozen co-bound coordinates plus material scene/frame anchors. Coverage is exhaustive over retained bindings but never combinatorial: no subsets, alternates, duplicate bundles, neighboring-proposition leakage, or scene-wide supersets. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V71_CLASS_RULES = {
    "PLACE": "PLACE = materially distinct setting or occurrence-position. Keep explicit broad/contained settings when both organize distinct material. Keep supported unnamed places when a materially distinct participant/object location, destination, waiting position, later interaction/conversation, remembered/prospective scene, or present telling is real but unnamed. A spatial noun/phrase is not automatically PLACE: if it names a conceptual/figurative thing, use OBJECT; if it orients another relation, use LOCATOR. Reject surfaces, body parts, support points, path points, movement endpoints, and spatial-looking phrases that do not establish a scene. Do not duplicate a thing as PLACE when its only job is OBJECT.",
    "TIME": "TIME = materially distinct scene-level temporal/event frame in source progression. Keep stages that organize represented material: attempts/conditions, response/help episodes, departures/transitions, waits, later conversations/reports, remembered episodes, recurring spans, present telling/reflection, and prospective frames when they are distinct frame anchors. Several relations may share one TIME. Reject predicate/action/question micro-times, local subactions, contemplated acts that do not establish their own frame, tense/aspect packaging, bare durations, adverbs, and descriptive clauses.",
    "PERSON": "PERSON = speaker B plus every materially represented human/social actor or stable group after coreference, including indirect, possessive, relational, offscreen, remembered, reported, prospective, and comparison actors. Resolve true aliases/coreference; exclude generic rhetorical addressees and classification words that do not denote represented actors.",
    "OBJECT": "OBJECT = materially represented independently selectable concrete or abstract thing. Keep source-distinguished wholes/parts, values/amounts, services/results, decisions/next steps, contemplated choices treated as things, stable relations/situations/plans, named sets/categories, and independently represented figurative/comparison referents. A comparison vehicle may be OBJECT when represented as a thing. Reject whole assertions/questions, explanation clauses, event restatements already carried by TIME/VERB, transient argument phrases, grammatical placeholders, and referents whose only job is PLACE.",
    "LABEL": "LABEL = independently selectable exact source-present characterization value: quality, state, evaluation, comparison, identity/classification, correction/rejection, polarity/status, experiential/epistemic description, or material manner. Use the shortest complete source-native value. Preserve uncertainty, question, negation, intensity, correction, contrast, and idiom when part of the value. A participial/verb-shaped form belongs in LABEL when its job is characterization rather than an independently selectable event. A questioned characterization and its explicit correction/rejection may each be LABEL when separately staged as candidate and answer. Reject whole propositions, question sentences, reason clauses, and predicate packets when a smaller characterization carries the job.",
    "VERB": "VERB = materially represented lexical relation/predicate increment. Keep principal relations and coordinated/embedded relations only when each has its own represented relational job; keep cognition/stance/report/recall/perception/intention/comparison/location/waiting only when they materially add relation, posture, modality, or attribution. Use the smallest semantically complete exact source-native construction. Ordinary subjects, objects, recipients, topics, and optional complements belong in compounds. Retain a particle/reflexive/negation/required complement only when lexically necessary for relation identity. A state/participle functioning only as characterization belongs in LABEL. Reject auxiliaries, support packaging, question/discourse wrappers, whole propositions, and every-parseable-subpredicate inflation.",
    "LOCATOR": "LOCATOR = selected exact source-native orientation/context relation independently positioning a retained person/object/event/relation. Keep material position, containment, support, proximity, path, direction, origin/destination, accompaniment, recurrence/context, embodied/internal orientation, and separable directional/adverbial constructions when the orientation/context itself is independently selectable. Split VERB relation atom from LOCATOR orientation when both jobs are separately represented. If a particle/complement is inseparable from lexical verb meaning, keep it with VERB and do not duplicate as LOCATOR. Use the smallest complete meaningful construction, not an isolated preposition. Reject recipients, topics, instruments, bare durations, discourse/causal phrases, and generic complements without a distinct orientation job.",
}
