"""Neutral V72 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V72_BASE_RULES = """
V72 ARCHETYPAL LIGHTWEIGHT RULE: read the whole source and reconstruct materially distinct scenes/episodes before extracting lexical classes. A primitive survives only with source support, a genuine class-specific researcher job, independent selectability, material contribution to the represented map, and non-redundancy. Explicitness, vividness, grammar, clausehood, and parseability do not create coordinates. Reject incidental scene dressing, weak modifiers, support grammar, discourse-management predicates, proposition fragments, and duplicate projections. PLACE is an actual represented scene/occurrence-position; prefer the scene over spatial tokens and preserve supported unnamed scene anchors. TIME is a represented episode/frame; prefer the episode over temporal tokens and do not mint nested clock/adverb/duration frames unless they organize distinct material. OBJECT is a durable thing-like participant or independently represented abstract/figurative referent, not every noun or prop. LABEL is a materially selectable characterization, not an adjective census. VERB is the smallest independent lexical relation; ordinary arguments, auxiliaries, syntactic negation, and reporting/support packaging stay outside the atom unless lexically inseparable. Preserve polarity/posture in exact cues and compounds. LOCATOR is an independently selectable orientation/context relation, not every prepositional/adverbial phrase or TIME duplicate. Copy all source-derived strings character-for-character, including punctuation and dialect. Freeze primitives, then segment the source into local represented propositions and create one materially complete compound per binding, including all and only co-bound frozen coordinates plus material scene/frame anchors. Do not create one compound per primitive by default and never generate subsets, alternates, duplicate bundles, or scene-wide supersets. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V72_CLASS_RULES = {
    "PLACE": "PLACE = actual materially represented setting/occurrence-position for a distinct episode, interaction, co-presence configuration, destination, wait, remembered/later/prospective scene, or present telling. Explicit broad context survives only when represented material actually occurs there or it organizes relations. Preserve supported unnamed places with source_wording null and exact cue. Prefer scene identity over spatial wording. Reject mere context labels, surfaces, body parts, edges, support/path points, movement endpoints, figurative spaces, and things whose only job is OBJECT.",
    "TIME": "TIME = materially distinct episode, period, recurring span, transition, wait, remembered frame, present-reflection frame, or prospective frame organizing represented relations. Prefer episode/frame identity over lexical temporal tokens. Reject predicate/action/question micro-times, comparison-internal times, clock phrases, durations, adverbs, frequency tokens, tense/aspect, and nested subframes unless they independently organize distinct represented material. Do not duplicate one episode as inferred frame plus temporal phrase.",
    "PERSON": "PERSON = speaker B plus every materially represented human/social actor or stable group after coreference, including indirect, possessive, relational, offscreen, remembered, reported, prospective, and comparison actors when represented. Resolve true aliases; exclude generic rhetorical addressees and classification words that do not denote actors.",
    "OBJECT": "OBJECT = materially represented independently selectable thing that participates in, organizes, or is itself the object of represented research relations. Keep concrete/abstract things, values, services/results, decisions/next steps, contemplated choices-as-things, stable situations/plans, named sets/categories, and independently represented figurative/comparison referents. Reject incidental scene dressing, transient props, descriptive nouns, bare durations, whole assertions/questions, reason clauses, event restatements, generic placeholders, and referents whose only job is PLACE. Do not inventory every noun inside a comparison.",
    "LABEL": "LABEL = materially research-selectable characterization value: quality, state, evaluation, comparison, identity/classification, correction/rejection, polarity/status, or experiential/epistemic description. Use the shortest complete source-native value and preserve its posture. Reject adjective/modifier census, scene-detail qualities, rhetorical flourish, intensifiers, and local manner words whose removal leaves the represented map unchanged. Participial/state forms belong here when they characterize rather than assert an independent event.",
    "VERB": "VERB = materially independent lexical relation/predicate increment. Keep only relations whose removal erases a distinct represented binding, attribution, epistemic/modal relation, action, experience, intention, comparison, waiting, or movement relation. Embedded relations survive only when independently material. Use the smallest exact lexical atom: ordinary arguments, scene anchors, auxiliaries, tense/aspect, syntactic negation, and support/report packaging stay outside unless lexically inseparable. Preserve negation/question/uncertainty in exact cue and compound posture. Suppress discourse-management/metatelling predicates, support wrappers, comparison-internal/hypothetical subpredicates that merely elaborate another retained coordinate, characterization-only forms, and every-parseable-subpredicate inflation.",
    "LOCATOR": "LOCATOR = independently selectable exact source-native orientation/context relation positioning a retained person/object/event/relation. Keep material position, containment, proximity, path, direction, origin/destination, accompaniment, recurrence/context, embodied/internal orientation, and separable directional/adverbial constructions only when the orientation itself does research work. Reject every-preposition extraction, TIME duplicates, source-of-information phrases, instruments, topics, reasons, comparison fragments, discourse context, bare durations, and generic complements. Split from VERB only when lexical action identity survives without it and the orientation is independently selectable.",
}
