"""Neutral V73 Researcher Inventory task rules. No gold rows/counts/evaluator findings/holdout content."""

V73_BASE_RULES = """
V73 ARCHETYPAL LIGHTWEIGHT RULE: read the whole source and recover a broad literal source-present research-coordinate census, then type and bind it economically. Lightweight means structurally economical, NOT narrative-importance pruning. Preserve explicit settings, temporal frames and micro-event anchors, actors, concrete/abstract referents, props/background items, characterization values, lexical predicates (including reporting/cognition/meta-telling/local subevents), and meaningful orientation/context relations whenever they perform a legitimate class job or participate in a local source binding. Do not discard a coordinate because it looks like scene dressing, clutter, a weak detail, a transient prop, or a one-off mention. Reject only true alias duplicates, event restatements better represented by relation+participants, and pure grammatical filler with no semantic coordinate job. PLACE may include broad, nested, local, remembered, prospective, and present-telling locations. TIME may include broad and proposition-local frames when the source distinguishes them. OBJECT includes source-present ambient/prop/reified material. LABEL preserves source characterizations. VERB preserves source-explicit predicates, including reporting/cognition/narration when lexically represented. LOCATOR preserves complete meaningful relation/orientation phrases and may overlap other classes when it has a genuine relation job. Copy every source-derived string character-for-character, including punctuation and dialect. Freeze primitives only after source-support/type/literal/duplicate audit. Then segment the source into local propositions and create one complete local compound per binding, including all co-bound frozen coordinates plus applicable place/time anchors and posture. Do not generate pairwise subsets, duplicate alternates, invented links, or giant scene-wide compounds. Never target hidden gold, expected counts, evaluator findings, prior scored outputs, or holdout material.
"""

V73_CLASS_RULES = {
    "PLACE": "PLACE = source-present setting/occurrence-position, including broad, nested, local, destination/origin, waiting, remembered, reported, prospective, and present-telling locations when they locate represented material. Preserve multiple location coordinates when the source represents multiple usable occurrence positions. Supported unnamed places may use source_wording null with exact cue. Do not suppress a place merely because it is broad context or because another nested place exists.",
    "TIME": "TIME = source-present temporal frame/episode anchor, including broad periods, local micro-events, waits, durations, recurring, remembered, present, intended/future/prospective, and transition frames when they organize a source proposition. Preserve multiple temporal coordinates when distinct source propositions/cues support them, even when nested. Supported unnamed times may use source_wording null with exact cue.",
    "PERSON": "PERSON = speaker B plus every source-represented human/social actor or stable group after true coreference, including indirect, possessive, relational, offscreen, remembered, reported, prospective, comparison, and generic-but-represented actors. Resolve true aliases; exclude only rhetorical/grammatical addressees that do not denote represented actors.",
    "OBJECT": "OBJECT = source-present concrete or abstract thing/referent available for research or local binding. Preserve wholes/parts, props, ambient/background items, documents, products, services, amounts, decisions, plans, choices-as-things, relational entities, reified concepts, figurative/comparison referents, and named sets/categories. Do not discard items as scene dressing, clutter, transient props, or one-off details. Exclude pure grammar and whole-event restatements better represented by relation+participants.",
    "LABEL": "LABEL = source-present characterization, quality, state, evaluation, identity/classification, comparison value, correction/rejection, status, experiential or epistemic description. Preserve local/brief values when they carry a characterization job. Use the shortest complete source-native value with posture. A noun phrase functioning as a referent/reified thing is OBJECT rather than LABEL merely because abstract.",
    "VERB": "VERB = source-explicit lexical predicate/relation. Preserve actions, experiences, states-as-predicates, cognition, speech/reporting, perception, intention, movement, comparison, possession, waiting, narration/meta-telling, and local subevents when lexically represented. Do not suppress predicates merely as support/report/discourse packaging. Use the smallest semantically complete source-native predicate atom; pure auxiliaries need not become separate primitives. Preserve exact posture in cue/compound.",
    "LOCATOR": "LOCATOR = complete source-native relation/orientation phrase positioning or relating a retained person/object/event/predicate/frame. Preserve physical/figurative position, containment, proximity, path, direction, origin/destination, accompaniment, embodied/internal position, recurrence/context, particles, comparison relations, and other meaningful locating constructions. Cross-class overlap is allowed when the phrase has a genuine relation job. Do not mint isolated prepositions.",
}
