"""V80 semantic task rules: positive class-native saturation with bounded semantic deduplication."""

V80_BASE_RULES = r'''
V80 ARCHETYPAL LIGHTWEIGHT RULE: recover SOURCE-SUPPORTED RESEARCHER-RECONNECTABLE COORDINATES AT CLASS-NATIVE RESOLUTION. The target is neither semantic compression nor lexical census.

READ THE WHOLE SOURCE FIRST. Resolve broad source order, coreference, and materially distinct scene/episode shifts. Then process each requested class independently in this order:
(1) POSITIVE COVERAGE across the complete source for every coordinate that genuinely performs this class job;
(2) GRAIN at the smallest complete source-native span/frame;
(3) TYPE by source function, never surface part of speech;
(4) CROSS-CLASS AUDIT for genuinely different reconnectable jobs performed by the same source material;
(5) BOUNDED DEDUP/SUPPRESSION using only the allowed defect classes below;
(6) LITERAL LOCK.
Freeze all primitives only after every requested class is complete. Build compounds afterward from frozen primitives.

POSITIVE COVERAGE IS NOT CENSUS. Explicit mention alone does not force admission, but low salience, one-use occurrence, background placement, nesting, remembered/reported status, prospectivity, figurative use, uncertainty, negation, or lack of an explicit name are never sufficient reasons to suppress a genuine class-native coordinate.

BOUNDED SUPPRESSION: after positive coverage, remove only (a) true alias/coreference duplicates; (b) pure auxiliary/function/discourse grammar with no independent class job; (c) bare prepositions/path particles with no independent orientation job; (d) duplicate same-grain restatement/tokenization of one lexical relation; (e) analyst-created abstraction/paraphrase/inference; (f) arbitrary subparts with no independent source identity; (g) whole-clause/sentence/question/proposition wrappers not treated by the source as identifiable content, choice, plan, decision, relationship, situation, or object of thought; or (h) duplicate projections that perform the same researcher job. Do not invent other suppression tests.

GRAIN: choose the smallest COMPLETE source-native grain that preserves the class job. Keep particles, reflexives, directional/relational complements, negation-bearing construction, or idiomatic material when removing them changes lexical relation identity. Do not split one relation into token-level verbs. For LABEL preserve the shortest complete staged value/state. PLACE/TIME operate at represented scene/position and episode/period scale, including supported unnamed frames.

TYPE BY RESEARCH JOB. PLACE=physical/institutional scene or occurrence position. TIME=episode/phase/period/frame. PERSON=human/social actor or stable group. OBJECT=independently source-treated concrete/abstract referent/content. LABEL=staged value/state/quality/classification/evaluation/comparison/correction/status. VERB=content-bearing lexical relation/event. LOCATOR=orientation/path/context relation.

PLACE POSITIVE PASS: retain every distinct source-supported setting or occurrence position, including broad/contained settings when both are useful; interaction/wait/conversation locations; destinations/departures/arrivals; another participant's represented scene; spatially staged object positions when the position itself is reconnectable; remembered/reported/prospective/comparison settings; and present-telling location when represented. Supported unnamed PLACE is required for a distinct represented scene/location job when the exact place is not named: use null source_wording plus exact source cue. Do not suppress a real occurrence position merely because it is deictic/relational or also performs LABEL/LOCATOR work. Do not turn a concrete object into PLACE merely because it can contain/support something.

TIME POSITIVE PASS: retain every distinct source-supported attempt, action episode, interaction/help/conversation episode, wait, transition, remembered/reported scene, recurring span, stable period, prospective/future frame, comparison/imagined frame, and present reflection/telling. Dates, times-of-day, and durations qualify when they locate a material episode/period. Supported unnamed TIME is required when a materially distinct episode exists without explicit temporal naming. Do not create TIME from every tense cue, now/then, frequency word, duration question, clause boundary, or action phrase; it must organize an independent episode/period/frame.

PERSON POSITIVE PASS: retain B plus every distinct represented human/social actor or stable group after true coreference. Minor, possessive/relational, offscreen, remembered, reported, prospective, institutional, and comparison actors may qualify when source-established. Exclude only nonreferential grammatical/rhetorical addressees. A social term may also be LABEL when independently used as characterization/classification.

OBJECT POSITIVE PASS: retain independently source-treated concrete and abstract referents, including physical things, scene items, products/documents/parts, amounts/values, choices, decisions, plans, relationships, recurring situations, mental contents, comparison vehicles, and explicitly reified relations/content. One-off and low-salience referents may qualify. Do not suppress a scene item merely because it supports/locates another thing if the source also treats it as an independent referent. Reject pronoun/deictic/coreference duplicates, arbitrary noun fragments, and whole proposition/question/clause wrappers unless the source itself reifies that course of action/situation/content as an identifiable thing. Do not duplicate a setting as OBJECT when its only job is PLACE.

LABEL POSITIVE PASS: retain source-staged values, states, qualities, classifications, evaluations, comparisons, corrections, rejections, identities, manner/state descriptions, polarity responses, and statuses. Preserve question, negation, uncertainty, correction, contrast, intensity, and attribution at the shortest complete source-native grain. Do not create LABEL from every modifier or ordinary action predicate. The same span may also be VERB/LOCATOR/PLACE when each is a distinct reconnectable job.

VERB POSITIVE PASS: retain every materially distinct content-bearing lexical relation/event, including movement, possession, experience, cognition, speech/reporting, perception, intention, comparison, waiting, stance, gesture, copular/locative relation, questioning, telling, saying, finding, thinking, and other represented predicates. Preserve the shortest COMPLETE source-native lexical construction; keep required particles/reflexives/complements/idiomatic material. Split coordinated/matrix/embedded predicates only when they are genuinely distinct represented relations. Suppress pure auxiliaries/function grammar and true same-relation duplicates only; never suppress a relation merely for being background, embedded, local, or one-use.

LOCATOR POSITIVE PASS: retain materially distinct source-native orientation/context relations for relative position, containment, direction, origin/destination, path, entry/exit, proximity/distance, accompaniment/carrying, recurrence/situational context, embodied/internal orientation, and figurative/comparison orientation. Mere prepositional grammar is insufficient. Movement/deictic/comparison wording may also be VERB/PLACE/LABEL if each projection performs a genuinely different reconnectable job.

MANDATORY CROSS-CLASS AUDIT: cross-class overlap is not presumptively suspect. For each retained source span or supported unnamed frame, ask separately: what actor/referent/content? what value/state/classification? what lexical relation/action? what orientation/path/context? what physical scene/position? what episode/period frame? Preserve every independently source-supported job. Remove only alternative grammatical parses that duplicate the same job.

LITERAL LOCK: every source-derived non-null string must preserve source language character-for-character where schema requires source text. No synonym, repair, spelling cleanup, dialect normalization, number change, contraction expansion, punctuation cleanup, or inferred wording. Only genuinely unnamed PLACE/TIME may use null source_wording with exact source cue.

QUALITIES: qualities_available is boolean only and true only when qualities/descriptions are available for that coordinate or compound. Question, negation, uncertainty, intensity, or presence of a LABEL does not automatically make it true.

PRIMITIVE FREEZE ORDER: whole-source read/coreference -> positive class-native coverage -> grain -> type -> cross-class audit -> bounded dedup/suppression -> source order/qualities -> literal lock. Freeze primitives before compounds. Compounds cannot add, delete, merge, retype, or repair primitives.

COMPOUNDS: after primitive freeze, scan source order for materially distinct represented relations/states. Emit one smallest materially complete local compound for each relation/state that requires binding: operative VERB/LABEL/LOCATOR primitive(s), retained PERSON/OBJECT/value roles, and useful applicable PLACE/TIME frame(s). Standalone primitives need no compound. Do not emit pairwise closure, nested subset variants, alternate tokenizations, one-compound-per-primitive, one-compound-per-mention, clause-support bundles, or scene-wide mega-bundles.

FINAL AUDIT: COVERAGE—did every source-supported class-native coordinate receive a positive test before suppression? SUPPRESSION—was each deletion removed only for an allowed defect class? GRAIN—smallest complete source-native job? CROSS-CLASS—were distinct jobs preserved even with overlapping wording? COREFERENCE—true aliases merged? LITERAL—exact strings? COMPOUNDS—one materially distinct local relation each, frozen refs only? CANDIDATE—no promotion or APA identity.

Never target hidden counts or infer gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. Never access the sealed holdout during calibration.
'''.strip()

V80_CLASS_RULES = {
    "PLACE": r'''Run a positive whole-source PLACE pass before suppression. Retain every distinct represented physical/institutional setting or occurrence position, named or supported unnamed: broad/contained settings, interaction/wait/conversation positions, destinations/departures/arrivals, another participant's scene, spatially staged object positions, remembered/reported/prospective/comparison settings, and present-telling location when represented. Null source_wording is allowed only for genuinely unnamed supported frames with exact source cue. Suppress only true duplicate/non-place jobs, never merely low-salience/deictic/relational places.'''.strip(),
    "TIME": r'''Run a positive whole-source TIME pass before suppression. Retain every distinct attempt/episode/phase/wait/transition/conversation/remembered/reported/recurring/prospective/comparison/present-telling frame and stable period. Supported unnamed TIME is required for a materially distinct episode without explicit temporal naming. Bare deictics/frequency/duration questions/action clauses do not qualify unless they organize an independent episode/period.'''.strip(),
    "PERSON": r'''Run a positive whole-source PERSON pass. Retain B and every distinct represented human/social actor or stable group after true coreference, including minor, possessive/relational, offscreen, remembered, reported, prospective, institutional, and comparison actors when source-established. Exclude only nonreferential grammatical/rhetorical addressees.'''.strip(),
    "OBJECT": r'''Run a positive whole-source OBJECT pass. Retain independently source-treated concrete/abstract referents including low-salience scene items, products/documents/parts, amounts/values, choices, decisions, plans, relationships, recurring situations, mental contents, comparison vehicles, and reified content. Reject aliases/deictic duplicates, arbitrary fragments, and whole-clause wrappers unless source-reified. Do not suppress a referent solely because it is scene furniture.'''.strip(),
    "LABEL": r'''Run a positive whole-source LABEL pass. Retain source-staged value/state/quality/classification/evaluation/comparison/correction/rejection/identity/polarity/status at the shortest complete source-native grain, preserving question/negation/uncertainty/contrast/intensity/attribution. Do not turn every modifier or ordinary predicate into LABEL. Allow genuine cross-class jobs.'''.strip(),
    "VERB": r'''Run a positive whole-source VERB pass. Retain every materially distinct content-bearing lexical relation/event, including movement, possession, experience, cognition, reporting/speech, perception, intention, comparison, waiting, stance, gesture, copular/locative relations and other predicates. Use the shortest COMPLETE source-native construction; preserve necessary particles/reflexives/complements/idioms. Suppress only pure auxiliaries/function grammar and true same-relation duplicates.'''.strip(),
    "LOCATOR": r'''Run a positive whole-source LOCATOR pass. Retain materially distinct source-native orientation/context relations for relative position, containment, direction, origin/destination, path, entry/exit, proximity/distance, accompaniment/carrying, recurrence context, internal/embodied orientation, and figurative/comparison orientation. Bare prepositions are insufficient; allow genuine overlap with VERB/PLACE/LABEL.'''.strip(),
}
