"""V81 semantic task rules: whole-source coverage with independent-research-job entitlement."""

V81_BASE_RULES = r'''
V81 ARCHETYPAL LIGHTWEIGHT RULE: test the WHOLE SOURCE for each requested class, but emit only SOURCE-SUPPORTED RESEARCHER-RECONNECTABLE COORDINATES that pass an INDEPENDENT-RESEARCH-JOB ENTITLEMENT gate. The target is neither sparse semantic compression nor lexical/episode/cross-class census.

READ THE WHOLE SOURCE FIRST. Resolve broad source order, coreference, materially distinct scenes/periods, and materially distinct represented relations. Then process each requested class independently in this order:
(1) COVERAGE AUDIT across the complete source for every plausible class candidate;
(2) ENTITLEMENT — emit only if it has an independent research job;
(3) GRAIN — smallest complete source-native span/frame preserving that job;
(4) TYPE by researcher function, never surface grammar;
(5) CROSS-CLASS AUDIT — another projection is valid only if that class separately passes entitlement;
(6) ANTI-CENSUS / DEDUP — remove grammar, aliases, microframes, proposition shells, duplicate projections, and alternate tokenizations;
(7) LITERAL LOCK.
Freeze primitives only after every requested class is complete. Build compounds afterward from frozen primitives.

ENTITLEMENT ROUTES. A primitive must satisfy at least one: (A) RELATIONAL ROLE — independent actor/referent/value/relation/orientation role in a material represented relation; (B) SCENE/EPISODE ANCHOR — PLACE/TIME that locates a materially distinct physical/institutional scene, interaction, wait, transition, remembered/reported scene, recurring period, prospective/comparison frame, or present-telling frame at class-native scale; (C) STANDALONE SOURCE IDENTITY — an independently reconnectable thing/content/value/setting/relationship/choice/decision/recurring situation/comparison vehicle/stable group or other source-established coordinate. Explicit mention alone is not entitlement.

ANTI-CENSUS: do not admit pure function grammar; support surfaces/containers that merely locate another thing; predicate/subordinate-action micro-TIMEs; movement/path/recurrence/context phrases as PLACE without a distinct setting/occurrence position; participant names/amounts/full questions/propositions/discourse markers/ordinary relations as LABEL without staged value/state work; event nominalizations/meta-discourse/whole-clause shells as OBJECT without source reification; embedded/control/complement VERBs split from one complete relation without separate relation identity; bare grammatical prepositions as LOCATOR; aliases; duplicate projections; alternate tokenizations; analyst abstractions or arbitrary subparts.

PLACE: scene-level physical/institutional setting or occurrence position. Retain broad/contained settings when each is useful; distinct interaction/wait/conversation positions; source-established destinations/arrival/departure settings; remembered/reported/prospective/comparison scenes; present-telling location when represented. Supported unnamed PLACE is required only when a distinct scene/interaction/wait/present-telling position would otherwise be lost. Null source_wording only for genuinely unnamed supported frames with exact source cue. Do not infer PLACE from paths, movement phrases, recurrence phrases, support surfaces, containers, or action/conversation wording alone.

TIME: episode-scale or period-scale frame. Retain materially distinct action/interaction episodes, waits, transitions, remembered/reported scenes, recurring periods, prospective/comparison frames, stable spans, material date/time-of-day frames, and present reflection/telling. GROUP serial local actions inside the same episode unless the source marks a material episode transition. Do not create TIME for every predicate, subordinate event, question, intention, clause, tense/deictic/frequency/duration wording. Supported unnamed TIME is allowed only for a material episode without explicit temporal naming.

PERSON: retain B and every distinct represented human/social actor or stable group after true coreference when it has an independent social identity or relation role. Minor, possessive/relational, offscreen, remembered, reported, prospective, and institutional actors may qualify. A PERSON span is also LABEL only when separately used as characterization/classification.

OBJECT: independently source-established concrete/abstract referent/content. Retain physical things, products/documents/parts, amounts/values, choices, decisions, plans, relationships, recurring situations, mental contents, comparison vehicles, and source-reified courses of action/content. Reject pronoun/deictic duplicates, arbitrary noun fragments, event nominalizations/meta-discourse, and whole clause/question/proposition shells unless the source itself reifies that content/course/situation as an identifiable thing. Do not duplicate a setting as OBJECT when its only job is PLACE.

LABEL: source-staged value/state/quality/classification/evaluation/comparison/correction/rejection/identity/manner/status. Preserve the shortest complete source-native value phrase and its meaningful question/negation/uncertainty/correction/contrast/intensity/attribution. Do not use LABEL for participant names, amounts, full questions/propositions, discourse markers, or ordinary relation wording. A polarity response qualifies only when it directly stages acceptance/rejection/correction of a represented value/classification.

VERB: materially distinct content-bearing lexical relation at the smallest COMPLETE source-native grain. Preserve required particles, reflexives, negation-bearing construction, directional/relational complements, and idiomatic material when removal changes relation identity. Matrix/control/complement chains remain ONE complete lexical relation when the embedded predicate merely completes the matrix relation. Split serial/coordinated/matrix/embedded predicates only when the source establishes genuinely independent relation jobs with distinguishable role structure or event identity. A contemplated coordinated course of action may remain one complete VERB. Suppress pure auxiliaries and same-relation alternate tokenizations.

LOCATOR: source-native orientation/path/context relation independently reconnectable from the action/referent. It may express relative position, containment, direction, origin/destination, path, entry/exit, proximity/distance, accompaniment/carrying, recurrence context, embodied/internal orientation, or figurative/comparison orientation. Bare prepositions, generic context, or movement wording are insufficient. Cross-class overlap requires separate entitlement in each class.

CROSS-CLASS AUDIT: the fact that wording performs one valid job never creates entitlement in another class. PLACE/TIME are not generic context shadows. LABEL is not a grammatical shadow for predicates. LOCATOR is not every prepositional complement. OBJECT is not every nameable proposition. Preserve overlap only when each class answers a distinct independently reconnectable research question.

LITERAL LOCK: every source-derived non-null string must preserve source language character-for-character where schema requires source text. No synonym, repair, spelling cleanup, dialect normalization, number change, contraction expansion, punctuation cleanup, or inferred wording. Only genuinely unnamed PLACE/TIME may use null source_wording with exact source cue.

QUALITIES: qualities_available is boolean only and true only when qualities/descriptions are available for that coordinate or compound. Question, negation, uncertainty, intensity, or presence of a LABEL does not automatically make it true.

PRIMITIVE FREEZE ORDER: whole-source read/coreference + coarse scene/relation ledger -> class coverage audit -> entitlement -> grain/type -> bounded cross-class audit -> anti-census/dedup -> source order/qualities -> literal lock. Freeze primitives before compounds. Compounds cannot add, delete, merge, retype, or repair primitives.

COMPOUNDS: after primitive freeze, use the coarse relation ledger. Emit one smallest materially complete local compound per materially distinct represented relation/state that needs binding, using defining VERB/LABEL/LOCATOR primitives, retained PERSON/OBJECT/value roles, and useful applicable PLACE/TIME anchors. Standalone primitives need no compound. Do not emit pairwise closure, nested subset variants, alternate tokenizations, one-compound-per-primitive, one-compound-per-mention, clause-support bundles, or scene-wide mega-bundles.

FINAL AUDIT: COVERAGE—every plausible class candidate tested? ENTITLEMENT—every emitted primitive has an independent research job? SCALE—PLACE/TIME scene/episode scale? GRAIN—VERB/LABEL smallest complete job? CROSS-CLASS—each projection independently earned? COREFERENCE—aliases merged? LITERAL—exact strings? COMPOUNDS—one material local relation each, frozen refs only? CANDIDATE—no promotion or APA identity.

Never target hidden counts or infer gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. Never access the sealed holdout during calibration.
'''.strip()

V81_CLASS_RULES = {
    "PLACE": r'''Run a whole-source PLACE coverage audit, then apply entitlement. Emit only distinct scene-level physical/institutional settings or occurrence positions with an independent setting/anchor job: useful broad/contained settings, material interaction/wait/conversation positions, source-established destinations/arrival/departure settings, remembered/reported/prospective/comparison scenes, and present-telling location when represented. Use null source_wording only for a genuinely unnamed distinct scene position that would otherwise be lost. Do not make PLACE from movement/path/recurrence wording, support surfaces, containers, or action phrases without a distinct occurrence-position job.'''.strip(),
    "TIME": r'''Run a whole-source TIME coverage audit, then apply entitlement at episode/period scale. Retain materially distinct interaction/action episodes, waits, transitions, remembered/reported scenes, recurring periods, prospective/comparison frames, stable spans, material date/time-of-day frames, and present telling. Group serial local actions inside the same episode unless a material episode transition exists. Do not make a TIME for every predicate, subordinate event, question, intention, clause, tense/deictic/frequency/duration wording.'''.strip(),
    "PERSON": r'''Run a whole-source PERSON coverage audit. Retain B and distinct represented human/social actors or stable groups after true coreference when they have independent social identity or a material relation role. Minor, possessive/relational, offscreen, remembered, reported, prospective, and institutional actors may qualify. Do not project PERSON wording into LABEL unless it independently characterizes/classifies.'''.strip(),
    "OBJECT": r'''Run a whole-source OBJECT coverage audit. Retain independently source-established physical/abstract referents, products/documents/parts, amounts/values, choices, decisions, plans, relationships, recurring situations, mental contents, comparison vehicles, and source-reified courses/content. Reject deictic aliases, arbitrary noun fragments, event nominalizations/meta-discourse, and whole clause/question/proposition shells unless the source itself reifies them as identifiable content.'''.strip(),
    "LABEL": r'''Run a whole-source LABEL coverage audit. Emit only independently staged value/state/quality/classification/evaluation/comparison/correction/rejection/identity/manner/status at the shortest complete source-native grain. Preserve meaningful posture. Do not use LABEL for participant names, amounts, full questions/propositions, discourse markers, or ordinary relation wording without an independent staged-value job.'''.strip(),
    "VERB": r'''Run a whole-source VERB coverage audit. Emit materially distinct lexical relations at the smallest COMPLETE source-native grain. Preserve necessary particles/reflexives/complements/idioms. Keep matrix/control/complement chains together when the embedded predicate only completes one relation. Split serial/coordinated/embedded predicates only when they have genuinely independent role structure or event identity. Suppress auxiliaries and alternate tokenizations of the same relation.'''.strip(),
    "LOCATOR": r'''Run a whole-source LOCATOR coverage audit. Emit only independently reconnectable orientation/path/context relations for relative position, containment, direction, origin/destination, path, entry/exit, proximity/distance, accompaniment/carrying, recurrence, internal orientation, or figurative/comparison orientation. Bare prepositions, generic context, and movement wording are insufficient without a separately queryable orientation job.'''.strip(),
}
