"""V82 semantic task rules: source-staged selectable-coordinate inventory with lexical saturation."""

V82_BASE_RULES = r'''
V82 ARCHETYPAL LIGHTWEIGHT RULE: inventory SOURCE-STAGED RESEARCHER-SELECTABLE COORDINATES. The target is broader than semantic summary but narrower than lexical/grammatical census. A coordinate belongs when a later researcher can reconnect to a distinct source-staged actor, referent/content, value/state, lexical relation/happening, orientation, scene, or episode without inventing meaning.

READ THE WHOLE SOURCE FIRST. Resolve source order, true coreference, materially distinct scenes/periods, and represented relations/happenings. For every requested class use: (1) POSITIVE COVERAGE of all plausible source-staged candidates across the whole source, including low-salience/nested/one-use/reported/remembered/prospective/uncertain/negative/figurative material; (2) SELECTABILITY — retain a distinct class-native source handle even if it is not central, repeated, or used in a compound; (3) GRAIN — smallest complete source-native unit preserving that handle; (4) TYPE by researcher function; (5) CROSS-CLASS TEST for a distinct class-native handle; (6) BOUNDED SUPPRESSION only for function grammar, true aliases, unreified shells, class shadows, arbitrary analyst subparts, and duplicate/alternate tokenizations; (7) LITERAL LOCK. Freeze primitives only after every class is complete. Build compounds afterward.

PRIMITIVES DO NOT NEED COMPOUNDS. Primitive coverage is broader than compound coverage. Low salience, nesting, background placement, one-use appearance, or no dedicated compound are never by themselves suppression reasons.

PLACE: source-staged physical/institutional setting or occurrence position. Retain useful broad/contained settings; distinct interaction, wait, conversation, arrival/departure, participant-location, remembered/reported, comparison, and present-telling positions; and supported unnamed positions when a distinct represented scene position would otherwise disappear. Null source_wording only for genuinely unnamed supported positions with exact source cue. Do not promote every place-bearing noun, path, support surface, container, or movement phrase into PLACE unless it is staged as a setting/position.

TIME: source-staged episode, period, transition, span, or materially useful temporal frame. Retain distinct attempts/interactions, waits, transitions, remembered/reported episodes, recurring spans, prospective/future frames, comparison/imagined frames, stable relationship periods, material date/time-of-day frames, and present reflection/telling. Supported unnamed TIME is allowed for a distinct episode without explicit temporal naming. Do not inventory every tense marker, frequency word, duration phrase, deictic, subordinate clause, or predicate as TIME.

PERSON: retain B and every distinct represented human/social actor or stable group after true coreference when the source gives a distinguishable role or identity. Minor, possessive/relational, offscreen, remembered, reported, prospective, and institutional actors may qualify. Exclude only nonreferential addressees and aliases. PERSON wording becomes LABEL only when separately staged as characterization/classification.

OBJECT: retain source-established concrete/abstract referents and content: physical things, products/documents/parts, amounts/values, choices, decisions, plans, relationships, recurring situations, mental contents, comparison vehicles, and other reconnectable things. Low-salience scene objects may qualify without compounds. Reject pronoun/deictic duplicates, arbitrary noun fragments, pure meta-discourse, and unreified whole-clause/proposition shells. Do not duplicate a setting as OBJECT when its only job is PLACE.

LABEL: source-staged value/state/quality/classification/evaluation/comparison/correction/rejection/identity/manner/status made separately selectable. Preserve shortest complete source-native value phrase and posture. Descriptive properties do not automatically become LABELs: when wording merely supplies qualities of another retained coordinate, prefer that coordinate's qualities_available unless the source separately foregrounds/stages the value/classification. Do not make LABELs from participant names, amounts, whole propositions, ordinary relation wording, every adjective/adverb, or grammar shadows.

VERB — POSITIVE LEXICAL RELATION SATURATION: retain each distinguishable source-staged content-bearing lexical relation/happening that a researcher could select as what happened, was done, perceived, said, thought, intended, possessed, located, compared, changed, or otherwise related. Low-salience, nested, reported, serial, speech/perception/cognition, copular/locative, and subordinate relations may qualify independently. Use the smallest COMPLETE lexical relation. Preserve particles, reflexives, negation-bearing construction, idiomatic material, and complements when removal changes identity. DO NOT merge separately asserted serial or nested predicates merely because they share subject, episode, causal chain, or clause. If the source separately predicates A and B, both may be VERBs. Merge only a genuinely lexicalized/control construction where embedded wording does not separately assert a selectable happening, or one explicitly contemplated coordinated course presented as a single candidate action. Suppress pure auxiliaries and true alternate tokenizations.

LOCATOR — SOURCE-NATIVE ORIENTATION SATURATION: retain orientation/position/path/context phrases that tell where, from where, toward where, through what, in relation to what, or in what materially useful orientation a represented coordinate/relation is staged. Include direct physical positions, containment/surface relations, direction, origin/destination, entry/exit, path, proximity/distance, accompaniment/carrying, recurrence context, embodied/internal orientation, and materially useful figurative/comparison orientation. A simple prepositional phrase may qualify when it genuinely locates/orients something; it need not be conceptually independent from the event. Exclude provenance, ownership, association, attribution, and generic context merely expressed prepositionally. Movement wording may overlap VERB and LOCATOR when it separately supplies both happening and orientation/path handles.

CROSS-CLASS AUDIT: overlap is allowed when wording genuinely supplies different selectable handles in different classes. Do not create mechanical shadows: PLACE/TIME for every relation, LABEL for every modifier/predicate, OBJECT for every proposition, or LOCATOR for every prepositional complement. Ask what distinct class-native handle a researcher would select.

LITERAL LOCK: every source-derived non-null string must preserve source language character-for-character where schema requires source text. No synonym, grammar repair, spelling cleanup, dialect normalization, number change, contraction expansion, punctuation cleanup, or inferred wording. Only genuinely unnamed PLACE/TIME may use null source_wording with exact source cue.

QUALITIES: qualities_available is boolean only. Set true when source qualities/descriptions are available for that coordinate or compound, including where those qualities are not separately inventoried as LABELs. Question/negation/uncertainty/intensity alone does not make it true.

PRIMITIVE FREEZE: whole-source read/coreference/scene-relation ledger -> positive class coverage -> selectability -> grain/type -> cross-class audit -> bounded suppression/dedup -> source order/qualities -> literal lock. Freeze before compounds. Compounds cannot add/delete/merge/retype/repair primitives.

COMPOUNDS — SELECTIVE BINDING LAYER: build a compound only when multiple frozen coordinates need binding to reconnect a focal source-level relation, state, episode event, comparison, or explicitly staged proposition. Use the smallest materially complete local binding with defining VERB/LABEL/LOCATOR roles, retained PERSON/OBJECT/value roles, and useful applicable PLACE/TIME anchors. A compound may include multiple VERBs when they jointly constitute the source's focal local event. Standalone/descriptive primitives need no compound. Do not emit pairwise closure, nested subset variants, alternate tokenizations, one-compound-per-primitive, one-compound-per-mention, clause-support bundles, or scene-wide mega-bundles.

FINAL AUDIT: COVERAGE—low-salience/nested source-staged coordinates tested? SELECTABILITY—each primitive a distinct class-native handle, whether or not compounded? SCALE—PLACE/TIME useful settings/frames, not shadows/raw tokens? LEXICAL SATURATION—distinct predicates and orientation relations not merged away? SUPPRESSION—grammar/shells/aliases/shadows removed without thinning source coordinates? COREFERENCE correct? LITERAL exact? COMPOUNDS selective focal bindings only? CANDIDATE only?

Never target hidden counts or infer gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. Never access the sealed holdout during calibration.
'''.strip()

V82_CLASS_RULES = {
    "PLACE": r'''Run whole-source positive PLACE coverage. Retain source-staged physical/institutional settings and occurrence positions, including useful broad/contained settings, distinct interaction/wait/conversation/arrival/departure/participant locations, remembered/reported/comparison/present-telling positions, and supported unnamed scene positions that would otherwise disappear. Do not promote every place-bearing noun, path, surface/container, or movement phrase unless it is actually a setting/position handle.'''.strip(),
    "TIME": r'''Run whole-source positive TIME coverage. Retain source-staged episodes, periods, transitions, waits, recurring spans, remembered/reported/prospective/comparison frames, stable relationship periods, material date/time-of-day frames, and present telling. Supported unnamed episodes may qualify. Do not inventory every tense/deictic/frequency/duration expression, subordinate clause, or predicate as TIME.'''.strip(),
    "PERSON": r'''Run whole-source PERSON coverage. Retain B and every distinct represented human/social actor or stable group after true coreference when source gives a distinguishable role/identity, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors. Suppress true aliases and nonreferential addressees.'''.strip(),
    "OBJECT": r'''Run whole-source OBJECT coverage. Retain source-established concrete/abstract referents/content, including low-salience physical things, products/documents/parts, amounts/values, choices/decisions/plans, relationships, recurring situations, mental contents, and comparison vehicles. Reject deictic aliases, arbitrary fragments, pure meta-discourse, and unreified clause/proposition shells.'''.strip(),
    "LABEL": r'''Run whole-source LABEL coverage. Retain separately staged values/states/qualities/classifications/evaluations/comparisons/corrections/rejections/identities/statuses at shortest complete source-native grain. Do not turn every descriptive quality into a LABEL; ordinary qualities of another coordinate may remain available through qualities_available unless separately foregrounded/staged.'''.strip(),
    "VERB": r'''Run positive lexical relation saturation across the whole source. Retain each distinguishable source-staged content-bearing relation/happening, including low-salience, nested, reported, serial, speech/perception/cognition, copular/locative, and subordinate predicates when separately asserted. Use the smallest complete lexical relation. Do not merge separately asserted predicates merely because they share subject/episode/clause. Merge only genuinely lexicalized/control constructions without a separately asserted embedded happening, or one explicitly contemplated coordinated course presented as a single candidate action. Suppress auxiliaries and true alternate tokenizations.'''.strip(),
    "LOCATOR": r'''Run source-native orientation saturation. Retain phrases that genuinely locate/orient a represented coordinate/relation: direct physical positions, containment/surfaces, direction, origin/destination, entry/exit, path, proximity/distance, accompaniment/carrying, recurrence context, internal orientation, and useful figurative/comparison orientation. Simple prepositional phrases can qualify when they truly orient. Exclude provenance/ownership/association/attribution/generic context merely because it is prepositional.'''.strip(),
}
