"""V83 semantic task rules: independent research handle or topology-bearing support gate."""

V83_BASE_RULES = r'''
V83 ARCHETYPAL LIGHTWEIGHT RULE: recover the source's MINIMUM SOURCE-FAITHFUL RESEARCH TOPOLOGY. The inventory is broader than summary but narrower than token/phrase/clause/predicate/preposition census.

READ THE WHOLE SOURCE FIRST. Resolve source order, true coreference, materially distinct scenes/periods, represented relations, transitions, and orientations. For every requested class use: (1) WHOLE-SOURCE COVERAGE of all plausible candidates, including low-salience, nested, one-use, reported, remembered, prospective, uncertain, negative, and figurative material; (2) ADMISSION GATE; (3) CLASS-NATIVE GRAIN; (4) TYPE by researcher function; (5) CROSS-CLASS ENTITLEMENT; (6) BOUNDED SUPPRESSION; (7) LITERAL LOCK. Freeze primitives only after all classes are complete. Build compounds afterward.

ADMISSION GATE — retain a candidate only if at least one route passes:
A. INDEPENDENT RESEARCHER HANDLE: the source gives enough stable/reconnectable identity that a later researcher can select it as a distinct item of that class without reconstructing it from another retained coordinate.
B. TOPOLOGY-BEARING SUPPORT COORDINATE: omission would collapse, disconnect, merge, or materially misstate two distinct source scenes, frames, participants, material relations, transitions, paths, positions, or orientations.
This is not a lexical-support route. Grammar, local predicate detail, modifiers, or prepositional complements do not qualify merely because they help describe an already represented edge.

NEGATIVE TOPOLOGY TEST: reject material when removing it leaves the same researcher topology intact because it only restates an already retained relation/value/state/orientation; supplies auxiliary/control/copular/support grammar; adds clause-local lexical detail; names an unreified proposition shell; duplicates ordinary quality/state predication; supplies generic prepositional/deictic/associative/provenance/ownership/attribution context; creates a microframe inside a retained episode; or is an alternate tokenization/class shadow. Low salience, one-use occurrence, reporting, uncertainty, figurative form, or no compound membership are NOT rejection reasons.

PLACE: scene/setting/occurrence-position scale. Retain broad/contained settings when each has independent research use. Admit a supported unnamed PLACE only when a distinct represented position/scene would otherwise disappear or merge incorrectly. Do not create PLACE from every location-bearing noun, surface, path, object position, movement phrase, or deictic.

TIME: episode/period/transition/recurring-span/remembered-reported/prospective/comparison/present-reflection scale. Admit supported unnamed TIME when a distinct represented frame would otherwise disappear or merge. Do not create TIME from every predicate, subordinate event, question, intention, tense marker, duration token, or clause. Local actions normally remain inside retained episodes unless a material transition or independently reconnectable frame exists.

PERSON: retain B and every distinct represented human/social actor or stable group after true coreference when source gives a distinguishable identity or participant role, including minor/relational/offscreen/reported/prospective/institutional actors. Suppress aliases and nonreferential addressees.

OBJECT: source-reified or independently reconnectable concrete/abstract referent/content. Retain physical things, products/documents/parts, amounts/values, choices, decisions, plans, relationships, recurring situations, mental contents, comparison vehicles, and other stable thing/content coordinates. Reject deictic aliases, arbitrary fragments, meta-discourse, and merely nameable unreified clause/proposition shells.

LABEL: separately source-staged value/state/quality/classification/evaluation/comparison/correction/rejection/identity/manner/status. Use shortest complete source-native value phrase. Ordinary descriptive or predicative wording is not automatically LABEL; use qualities_available unless source separately foregrounds/stages the value/classification as its own research handle.

VERB — MATERIAL RELATION EDGES, NOT PREDICATE CENSUS: retain the minimal complete source-native relation only when it supplies independently useful research access OR omission would erase a materially distinct action/change/transfer/choice/report/perception/speech/cognition-intention/location relation/other topology edge. A content-bearing predicate is not automatically a VERB. Do not inventory every copular clause, descriptive predication, embedded completion, subordinate predicate, serial support relation, or lexical token. Matrix/control/complement chains remain one relation unless the embedded relation introduces a separately staged participant/content/state/choice/trajectory that is independently reconnectable or topology-bearing. Serial/coordinated actions split only when source stages independently selectable material edges; one contemplated course may remain one relation. Suppress auxiliaries and alternate tokenizations.

LOCATOR — MATERIAL ORIENTATION EDGES, NOT PREPOSITION CENSUS: retain materially queryable position/containment/direction/origin-destination/entry-exit/path/proximity-distance/accompaniment-carrying/internal/figurative orientation. A simple deictic or prepositional span may qualify when omission removes independent orientation access or breaks a material topology edge. Exclude provenance, ownership, association, attribution, topic/recipient grammar, generic context, and every prepositional/deictic fragment. Movement may overlap VERB/LOCATOR only when both materially distinct jobs exist.

CROSS-CLASS ENTITLEMENT: same wording may appear in multiple classes only when dropping one projection removes a genuinely different researcher question/handle or topology edge. A valid coordinate in one class does not create a shadow in another.

LITERAL LOCK: preserve source language character-for-character for every source-derived non-null field where schema requires source text. No synonyms, grammar repair, dialect normalization, number changes, contraction expansion, punctuation cleanup, or invented wording. Only genuinely unnamed PLACE/TIME may use null source_wording with exact source cue.

QUALITIES: qualities_available is boolean only. Set true when source-present qualities/descriptions are available. It does not force a separate LABEL.

PRIMITIVE FREEZE: whole-source coverage -> admission routes -> class-native grain/type -> cross-class entitlement -> coreference/order/qualities -> negative topology suppression -> literal lock. Freeze before compounds. Compounds cannot add/delete/merge/retype/repair primitives.

COMPOUNDS — SELECTIVE FOCAL BINDINGS: build a compound only when multiple frozen coordinates need binding to reconnect a focal source-material relation, state, transition, comparison, or explicitly staged proposition. Use the smallest materially complete local binding with defining relation/value/orientation roles, participating PERSON/OBJECT roles, and useful PLACE/TIME anchors. Several relation primitives may share one compound when source presents one inseparable focal event. Split only independently selectable material relations. No pairwise closure, nested subsets, alternate tokenizations, one-compound-per-primitive, clause-support bundles, or scene-wide mega-bundles.

FINAL AUDIT: test low-salience/nested candidates; verify every primitive passes handle or topology route; remove lexical/support/shadow material whose omission leaves topology unchanged; keep PLACE/TIME at scene/episode scale; keep VERB at material relation-edge grain; keep LOCATOR at material orientation-edge grain; require independent cross-class value; preserve coreference/literal language; emit selective compounds only; remain candidate-only.

Never target hidden counts or infer gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. Never access the sealed holdout during calibration.
'''.strip()

V83_CLASS_RULES = {
    "PLACE": r'''Run whole-source PLACE coverage, then retain only independently reconnectable settings/positions or topology-bearing scene anchors. Supported unnamed positions may qualify when a distinct represented scene would otherwise disappear or merge. Keep scene scale; reject incidental surfaces, object positions, movement/path fragments, and deictics that do not independently preserve spatial topology.'''.strip(),
    "TIME": r'''Run whole-source TIME coverage, then retain only independently reconnectable episode/period/transition frames or topology-bearing temporal anchors. Supported unnamed frames may qualify. Keep episode scale; reject predicate microframes, subordinate-event shadows, and raw temporal/deictic wording that does not distinguish a material frame.'''.strip(),
    "PERSON": r'''Retain B and every distinct represented human/social actor or stable group after true coreference when source gives a distinguishable identity or participant role, including minor, relational, offscreen, reported, prospective, and institutional actors. Suppress aliases and nonreferential addressees.'''.strip(),
    "OBJECT": r'''Retain source-reified or independently reconnectable concrete/abstract referents/content, including physical things, amounts/values, choices/decisions/plans, relationships, recurring situations, mental contents, and comparison vehicles. Reject deictic aliases, arbitrary noun fragments, meta-discourse, and unreified clause/proposition shells.'''.strip(),
    "LABEL": r'''Retain separately source-staged values/states/qualities/classifications/evaluations/comparisons/corrections/rejections/identities/statuses at shortest complete source-native grain. Ordinary descriptive/predicative wording remains qualities_available unless source separately stages it as an independent value/classification handle.'''.strip(),
    "VERB": r'''Retain minimal complete MATERIAL RELATION EDGES, not all content-bearing predicates. A relation qualifies when independently reconnectable or topology-bearing: omission would erase a materially distinct action/change/transfer/choice/report/perception/speech/cognition-intention/location relation or other source edge. Suppress copular/descriptive/support predicates, embedded completions, and serial/control fragments unless they introduce an independently staged participant/content/state/choice/trajectory or necessary topology edge. Split coordinated/serial actions only when independently selectable material edges exist.'''.strip(),
    "LOCATOR": r'''Retain materially queryable orientation/position/path edges: position, containment, direction, origin/destination, entry/exit, path, proximity/distance, accompaniment/carrying, internal or materially staged figurative orientation. A simple deictic/prepositional phrase qualifies only when independently useful or topology-bearing. Reject generic grammar, provenance, ownership, association, attribution, topic/recipient, and preposition/deictic census.'''.strip(),
}
