"""V84 semantic task rules: source-staged coordinate coverage at canonical class-native grain."""

V84_BASE_RULES = r'''
V84 ARCHETYPAL LIGHTWEIGHT RULE: inventory SOURCE-STAGED RESEARCH COORDINATES AT CANONICAL CLASS-NATIVE GRAIN. The target is broader than semantic summary and narrower than token/phrase/grammar/arbitrary-clause census.

READ THE WHOLE SOURCE FIRST. Resolve source order, true coreference, distinct settings/episodes, actors/referents, lexical relations, values/states, and contextual orientations. For every requested class use: (1) BROAD CANDIDATE COVERAGE, including low-salience/nested/one-use/reported/remembered/prospective/uncertain/negative/figurative/background material; (2) SOURCE-STAGED COORDINATE TEST; (3) CANONICAL GRAIN as the smallest complete source-native unit for one coordinate; (4) TYPE BY RESEARCH USE; (5) CROSS-CLASS ENTITLEMENT; (6) HARD-EXCLUSION SUPPRESSION only for aliases/pronoun duplicates, pure auxiliaries/function grammar, unsupported proposition shells, arbitrary analyst subparts, exact duplicate/alternate tokenizations, nonreferential rhetoric, and true class shadows; (7) LITERAL LOCK. Freeze primitives only after all classes are complete. Build compounds afterward.

SOURCE-STAGED COORDINATE PRESUMPTION: when the source distinctly stages a class-native actor, referent, setting/frame, value/state, lexical relation, or contextual orientation, presume it belongs unless a hard exclusion applies. Do NOT reject it merely because another coordinate captures the broad scene/event, it is background or one-use, omitting it leaves the narrative understandable, it is not central/repeated, or it has no compound. Preserve research reconnectability, not minimum narrative topology.

PLACE: represented physical/institutional setting or occurrence position. Retain explicit broad/contained settings and supported unnamed PLACE frames when participant configuration, interaction, wait, arrival/departure, reported/remembered scene, comparison scene, or present telling distinguishes a setting/position even without an explicit place phrase. Do not create PLACE from every noun/surface/path/object position. Unnamed PLACE may use null source_wording with exact source cue.

TIME: represented episode, period, transition, recurring span, remembered/reported frame, prospective frame, comparison frame, stable relationship period, material date/time-of-day frame, or present-reflection/telling frame. Retain supported unnamed TIME when source distinguishes an episode/frame even without explicit temporal wording. Distinct interactions, waits, departures, intended periods, recurring practice, later explanation/reflection, and future recurrence may form separate frames. Do not create TIME for every predicate/tense/frequency/duration/subordinate clause.

PERSON: retain B and every distinct represented human/social actor or stable group after true coreference when source gives a distinguishable identity or participant role, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors. Exclude aliases and nonreferential addressees.

OBJECT: retain source-established concrete/abstract referents/content, including low-salience physical things, products/documents/parts, scene objects, amounts/values, choices/decisions/plans, relationships, recurring situations, mental contents, comparison vehicles, and other actual referents. Distinguish materially different referents; merge only true coreference. Reject pronoun/deictic duplicates, arbitrary fragments, telling-management/meta-discourse, and event/proposition shells created only by nominalizing a clause without stable referent identity. Do not duplicate a setting as OBJECT when its only job is PLACE.

LABEL: retain atomic source-staged value/state/quality/classification/evaluation/comparison/correction/rejection/identity/manner/deictic-characterization/status handles. Prefer the atomic lexical value/state span over a whole proposition. Preserve question/negation/uncertainty/contrast/intensity only when part of the value itself. Do not turn a whole cognition, intention, action, question, or proposition into LABEL when its class-native job is VERB/OBJECT or ordinary predication. qualities_available can carry non-separate description.

VERB — SEPARATELY LEXICALIZED RELATIONS AT ATOMIC COMPLETE GRAIN: retain each distinguishable content-bearing lexical action/change/transfer/choice/report/perception/speech/cognition-intention/possession/location/other relation asserted or staged by the source. Low-salience, nested, subordinate, reported, serial, perception/help/control relations may qualify. Use smallest complete source-native relation; preserve particles/reflexives/required complements/negation when identity requires them. DO NOT OVER-MERGE: split matrix/control/complement or serial/coordinated constructions into separate VERB coordinates when source lexicalizes and predicates separate relations even if they share subject/object/clause/episode. Keep together only one genuinely lexicalized relation or explicitly single contemplated course whose internal words do not establish separately selectable happenings. Suppress pure auxiliaries, empty copular/support grammar, and alternate tokenizations.

LOCATOR — SOURCE-NATIVE CONTEXTUAL ORIENTATION: retain a source-native orientation/context handle that tells where, when-relative-to-what, from where, toward where, through what, with/along what, inside/outside what, across what recurring context, or in what represented comparative/figurative orientation a coordinate/relation is staged. Include position, containment/surface, direction, origin/destination, entry/exit, path, proximity/distance, accompaniment/carrying, recurrence/context anchoring, embodied/internal orientation, temporal-context orientation, and useful figurative/comparison orientation. Exclude generic syntax, pure ownership/provenance/attribution, and preposition census. Movement may overlap VERB/LOCATOR when each supplies a distinct research handle.

CROSS-CLASS ENTITLEMENT: overlap is allowed only when each projection answers a genuinely different class-native research question. No automatic PLACE/TIME for every relation, LABEL for every modifier/predicate, OBJECT for every proposition, or LOCATOR for every prepositional complement.

LITERAL LOCK: preserve source language character-for-character for every source-derived non-null field where schema requires source text. No synonyms, grammar repair, dialect normalization, number changes, contraction expansion, punctuation cleanup, or invented wording. Only genuinely unnamed PLACE/TIME may use null source_wording with exact source cue.

QUALITIES: qualities_available is boolean only. Set true when source-present qualities/descriptions are available; it does not force a LABEL.

PRIMITIVE FREEZE: whole-source coverage -> source-staged coordinate decisions -> canonical grain/type -> cross-class entitlement -> coreference/order/qualities -> hard exclusions -> literal lock. Freeze before compounds. Compounds cannot add/delete/merge/retype/repair primitives.

COMPOUNDS — ANCHOR-DRIVEN LOCAL PROPOSITION/EVENT BINDINGS: after freeze, build compounds from distinct local source propositions/events/states/orientations. A retained content VERB normally anchors one smallest materially complete local compound when at least one other frozen coordinate participates. A separately staged LABEL or LOCATOR may anchor a compound when it binds multiple coordinates without a better VERB anchor. Include only locally participating PERSON/OBJECT/relation/value/orientation units and useful PLACE/TIME anchors. Split compounds when source asserts separately selectable relations even in one sentence; combine multiple relations only for one inseparable source event/course. No pairwise closure, nested subset variants, alternate tokenizations, one-compound-per-primitive, whole-scene mega-bundles, or cross-proposition bundles.

FINAL AUDIT — MISSINGNESS FIRST, THEN OVERGENERATION: valid low-salience/nested coordinates not thinned for narrative minimality? distinct unnamed PLACE/TIME contexts reconstructed without predicate microframes? low-salience concrete OBJECTs retained while aliases/proposition shells suppressed? LABELs atomic? separately lexicalized VERBs split without auxiliary/support noise? contextual LOCATORs covered without preposition census? cross-class overlap independently entitled? literal/coreference exact? compounds local and anchor-driven? candidate-only?

Never target hidden counts or infer gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. Never access the sealed holdout during calibration.
'''.strip()

V84_CLASS_RULES = {
    "PLACE": r'''Run broad whole-source PLACE coverage. Retain every distinguishable represented setting/position, including explicit broad/contained settings and supported unnamed participant/interactions/wait/arrival-departure/reported/comparison/present-telling positions. Do not thin a valid setting because another broad scene already exists; do not promote every surface/path/object position.'''.strip(),
    "TIME": r'''Run broad whole-source TIME coverage. Retain every distinguishable represented episode/period/transition/wait/recurring/prospective/reported/comparison/present-telling frame, including supported unnamed frames. Do not thin a valid episode because a broader episode exists; do not create predicate/tense/frequency microframes.'''.strip(),
    "PERSON": r'''Retain B and every distinct represented human/social actor or stable group after true coreference when source gives a distinguishable role/identity, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors. Suppress true aliases and nonreferential addressees.'''.strip(),
    "OBJECT": r'''Run broad OBJECT coverage. Retain source-established concrete/abstract referents, especially low-salience physical scene objects as well as products/documents/parts, amounts/values, choices/decisions/plans, relationships, recurring situations, mental contents, and comparison vehicles. Merge only true coreference. Reject pronoun duplicates, arbitrary fragments, meta-discourse, and unsupported event/proposition shells.'''.strip(),
    "LABEL": r'''Retain atomic source-staged value/state/quality/classification/evaluation/comparison/correction/rejection/identity/manner/deictic-characterization/status handles. Prefer the smallest lexical value/state span; do not wrap a whole cognition/action/question/proposition as LABEL merely because it carries evaluative content.'''.strip(),
    "VERB": r'''Retain each separately lexicalized content-bearing source relation/happening at smallest complete grain, including low-salience, nested, subordinate, reported, serial, perception/help/control relations. Split separately predicated matrix/control/complement/serial relations even when sharing a clause. Keep together only one genuinely lexicalized relation or explicitly single contemplated course. Suppress pure auxiliaries/support grammar and alternate tokenizations.'''.strip(),
    "LOCATOR": r'''Retain source-native contextual orientations: spatial position/containment/direction/source-destination/path/proximity, accompaniment/carrying, recurrence or temporal-context anchoring, internal/embodied orientation, and useful figurative/comparison orientation. Simple deictic/context phrases may qualify when they give a distinct orientation handle. Exclude generic syntax, pure ownership/provenance/attribution, and preposition census.'''.strip(),
}
