"""V85 semantic task rules: bounded independently reconnectable coordinates at canonical class-native grain."""

V85_BASE_RULES = r'''
V85 ARCHETYPAL LIGHTWEIGHT RULE: inventory BOUNDED INDEPENDENTLY RECONNECTABLE RESEARCH COORDINATES AT CANONICAL CLASS-NATIVE GRAIN. The target is broader than semantic summary and narrower than token/phrase/grammar/predicate/preposition/arbitrary-clause census.

READ THE WHOLE SOURCE FIRST. Resolve source order, true coreference, materially distinct settings/episodes, actors/referents, lexical relations, values/states, and contextual orientations.

FOR EVERY REQUESTED CLASS use this order:
1. BROAD CANDIDATE CONSIDERATION — consider low-salience, nested, one-use, reported, remembered, prospective, uncertain, negative, figurative, and background material.
2. BOUNDED ADMISSION — retain only a source-staged class-native handle that is independently reconnectable OR materially required to preserve a distinct represented scene/frame/participant/referent/relation/value/orientation.
3. CANONICAL GRAIN AFTER ADMISSION — only after a coordinate qualifies, choose the smallest complete source-native unit expressing that coordinate. Atomic splitting is not itself an admission reason.
4. TYPE BY RESEARCH USE — classify by the class-native research question the coordinate supplies, not surface part of speech or spatial/temporal wording alone.
5. CROSS-CLASS ENTITLEMENT — overlap only when each projection independently supplies a different class-native research handle.
6. SUPPRESS SHADOWS/SUPPORT — aliases, pronoun/deictic duplicates, auxiliaries/function grammar, unreified proposition shells, arbitrary analyst subparts, exact duplicate tokenizations, metadiscourse, generic context, and class shadows.
7. LITERAL LOCK — preserve exact source language wherever a source-derived string is required.

BOUNDED ADMISSION ROUTE A — INDEPENDENT HANDLE: the source gives the candidate enough identity that a later researcher could select and reconnect to it as a distinct item of that class without reconstructing it merely from grammar or another retained coordinate. Low salience, one-use occurrence, reported status, uncertainty, figurative form, or background placement do not defeat admission.

BOUNDED ADMISSION ROUTE B — MATERIAL SUPPORT: the candidate is needed to preserve a materially distinct represented scene/frame/participant/referent/relation/value/orientation that would otherwise collapse, merge, or be mistyped. Lexical detail, grammatical support, modifier content, generic context, or a prepositional complement does not qualify merely because it adds information.

NEGATIVE CHECK: reject a candidate when removing it leaves the same class-native research access because it is only an alias/alternate tokenization, auxiliary/control/support grammar, local descriptive/temporal/spatial fragment already carried by another coordinate, unreified proposition/event shell, telling-management/metadiscourse, automatic cross-class shadow, or generic orientation/sequencing cue.

PLACE — REPRESENTED SETTING POSITIONS, NOT SPATIAL VOCABULARY: retain physical/institutional settings or occurrence positions at scene/interaction scale. Retain explicit broad/contained settings when independently represented. Reconstruct supported unnamed PLACE when a distinct interaction, wait, reported/remembered interpersonal scene, comparison scene, or present-telling situation has an occurrence position that would otherwise disappear or merge. Do not create PLACE merely because wording names space, distance, water, a path, an object position, community descriptor, or figurative spatial phrase. Spatial wording functioning as a referent, comparison vehicle, label, or locator should be typed by that use. Unnamed PLACE may use null source_wording with exact source cue.

TIME — EPISODE/PERIOD FRAMES, NOT TEMPORAL VOCABULARY: retain represented episodes, periods, transitions, recurring spans, remembered/reported frames, prospective frames, relationship periods, comparison frames, or present-telling/reflection frames at researcher-useful scale. Retain intended, recurring, future, remembered, reported, or present frames when independently staged. Reconstruct supported unnamed TIME where needed to keep such a frame distinct. Do not create TIME merely from a frequency word, duration phrase, tense marker, sequencing adverb, predicate, subordinate clause, or local action that remains within an already represented episode. Temporal wording may instead be LOCATOR or context only.

PERSON: retain B plus every distinct represented human/social actor or stable group after true coreference when the source gives a distinguishable identity or participant role, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors. Suppress true aliases and nonreferential addressees. PERSON wording is LABEL only when independently staged as characterization/classification.

OBJECT — REPRESENTED REFERENTS AND REIFIED CONTENTS: retain source-established concrete/abstract referents with independent identity, including low-salience physical things, products/documents/parts, scene objects, amounts/values, choices, decisions, plans, relationships, recurring situations, reified mental contents, and comparison vehicles. A spatially worded phrase may be OBJECT when its source job is referential rather than setting/orientation. Reject pronoun/deictic duplicates, arbitrary noun fragments, telling-management language, and proposition/event shells created only by nominalizing a clause. Do not duplicate a setting as OBJECT when its only job is PLACE.

LABEL — SEPARATELY STAGED VALUES/STATES/CLASSIFICATIONS: retain separately source-staged value, state, quality, classification, evaluation, comparison, correction, rejection, identity, manner, or status handles. Prefer the shortest complete source-native value/state span. Preserve question/negation/uncertainty/contrast/intensity/deictic wording only when it belongs to that value itself. Do not turn every adjective, number, degree phrase, temporal phrase, proposition, cognition, intention, or predicate into LABEL. Ordinary description may instead be qualities_available.

VERB — MATERIAL LEXICAL RELATIONS; ATOMIC GRAIN ONLY AFTER ADMISSION: first decide that the relation independently qualifies or materially preserves a represented relation edge. Then split admitted lexical relation chains to smallest complete relation grain. Split separately predicated matrix/control/complement, perception/help, or serial/coordinated relations when each is independently staged. But atomicity is NOT a predicate census. Suppress pure auxiliaries, do-support, empty copulas, aspect/support verbs, generic reporting scaffolding, infinitival support, metadiscourse, and lexical fragments whose only role is supporting another admitted relation. A contemplated course may remain one relation when source presents it as one selectable course rather than several independent happenings. Preserve particles/reflexives/required complements/negation when relation identity requires them.

LOCATOR — MATERIALLY QUERYABLE ORIENTATION: retain source-native orientation handles that materially tell where, from where, toward where, through what, inside/outside what, with/along what, relative to what time/context, or in what represented comparative/figurative orientation an admitted coordinate/relation is staged. Include material position, containment, direction, origin/destination, path, entry/exit, proximity/distance, accompaniment/carrying, recurring-context orientation, and materially staged figurative/comparison orientation. Do NOT inventory every deictic, sequencing adverb, temporal word, discourse relation, recipient phrase, ownership/provenance phrase, or prepositional complement. A locator must remain independently queryable after broad scene/frame coordinates are known. Movement may overlap VERB/LOCATOR only when each separately supplies a material research handle.

CROSS-CLASS ENTITLEMENT: surface spatial wording does not automatically mean PLACE; temporal wording does not automatically mean TIME; a predication does not automatically mean LABEL; a noun phrase does not automatically mean OBJECT; a preposition does not automatically mean LOCATOR. Each projection must independently earn its class-native research use.

LITERAL LOCK: preserve source language character-for-character for all source-derived non-null fields where schema requires source text. No synonyms, grammar repair, dialect normalization, number changes, contraction expansion, punctuation cleanup, or invented wording. Only genuinely unnamed PLACE/TIME frames may use null source_wording with exact source cue.

QUALITIES: qualities_available is boolean only. Set true when source-present qualities/descriptions are available. It does not force a separate LABEL.

PRIMITIVE FREEZE: broad candidate consideration -> bounded admission -> canonical grain/type -> cross-class entitlement -> coreference/order/qualities -> suppression -> literal lock. Freeze before compounds. Compounds cannot add/delete/merge/retype/repair primitives.

COMPOUNDS — LOCAL MATERIAL BINDINGS: after freeze, build compounds from distinct local material source propositions/events/states/orientations. An admitted material VERB normally anchors one smallest complete local compound when another frozen coordinate participates. A separately staged LABEL or LOCATOR may anchor a material state/orientation when no better VERB anchor exists. Include only materially participating PERSON/OBJECT roles, admitted relation/value/orientation units, and useful PLACE/TIME anchors. Split separately admitted relations into separately selectable local propositions; combine only when source presents one inseparable event/course. No pairwise closure, nested subset variants, alternate tokenizations, one-compound-per-primitive, grammatical-support bundles, whole-scene mega-bundles, or cross-proposition bundles.

FINAL AUDIT — BALANCE MISSINGNESS AND OVERGENERATION: all low-salience/nested/reported/remembered/prospective/negative/uncertain/figurative candidates considered? each retained primitive passes bounded admission independently of lexical separability? PLACE/TIME at scene/frame scale including necessary unnamed contexts without vocabulary census? real low-salience/abstract OBJECT referents retained while proposition shells suppressed? LABELs are separately staged values/states? VERBs split admitted relations atomically without support-grammar census? LOCATORs materially orient without preposition/deictic census? cross-class overlap independently entitled? literal/coreference exact? compounds local/material? candidate-only?

Never target hidden counts or infer gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. Never access the sealed holdout during calibration.
'''.strip()

V85_CLASS_RULES = {
    "PLACE": r'''Consider all source-staged settings, including low-salience and unnamed interaction/wait/reported/present-telling positions, but admit only independently represented scene/interaction-scale positions or material support settings. Do not convert spatial vocabulary, object positions, distance, water/path words, community descriptors, or figurative spaces into PLACE merely because they are spatial.'''.strip(),
    "TIME": r'''Consider all episodes/periods, including intended, recurring, future, remembered, reported, relationship, and present-telling frames, but admit only independently represented researcher-useful frames or material support periods. Do not turn frequency/duration words, sequencing adverbs, predicates, subordinate clauses, or local actions into TIME merely because they are temporal.'''.strip(),
    "PERSON": r'''Retain B and every distinct represented human/social actor or stable group after true coreference when source gives a distinguishable role/identity, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors. Suppress true aliases and nonreferential addressees.'''.strip(),
    "OBJECT": r'''Retain independently represented concrete/abstract referents, including low-salience physical scene objects, products/documents/parts, amounts/values, choices/decisions/plans, relationships, recurring situations, reified mental contents, and comparison vehicles. A spatial phrase may be OBJECT if referential. Reject pronoun duplicates, arbitrary fragments, metadiscourse, and unreified event/proposition shells.'''.strip(),
    "LABEL": r'''Retain only separately source-staged values/states/qualities/classifications/evaluations/comparisons/corrections/rejections/identities/manners/statuses that themselves provide a research handle. Prefer the shortest complete source-native value span. Do not inventory every modifier, number, degree phrase, temporal phrase, proposition, cognition, intention, or ordinary predicate; use qualities_available for ordinary description.'''.strip(),
    "VERB": r'''First admit only independently useful or materially topology-preserving content relations. THEN split admitted matrix/control/complement, perception/help, serial/coordinated relations to the smallest complete lexical relation when each is separately predicated. Atomicity is not predicate census: suppress auxiliaries, do-support, empty copulas, aspect/support verbs, generic reporting scaffolding, infinitival support, metadiscourse, and lexical support fragments.'''.strip(),
    "LOCATOR": r'''Retain only materially queryable source-native orientations of admitted coordinates/relations: position, containment, direction, origin/destination, path, entry/exit, proximity, accompaniment/carrying, recurring-context, or materially staged figurative/comparison orientation. Do not inventory every deictic, temporal/sequencing word, discourse relation, recipient phrase, ownership/provenance phrase, or prepositional complement.'''.strip(),
}
