"""V87 semantic task rules: complete accounting without primitive atomization."""

V87_BASE_RULES = r'''
V87 LIGHTWEIGHT RULE: ACCOUNT FOR ALL MATERIAL SOURCE CONTENT, BUT ADMIT ONLY BOUNDED RECONNECTABLE RESEARCH COORDINATES AS PRIMITIVES. The target is broader than summary and narrower than token/grammar/predicate/preposition/clause census.

READ THE WHOLE SOURCE FIRST.

SILENT SEMANTIC LEDGER: map material scenes/episodes, actors, referents, relations, values/states, choices/decisions, recurring relations, comparisons, and orientations. For each source detail distinguish two questions: (1) is it semantically accounted for somewhere in the candidate? (2) is it independently entitled to a primitive of the requested class? Every material detail should be accounted for; only entitled details become primitives. Literal preservation does NOT require one primitive per word/predicate/preposition.

PRIMITIVE ADMISSION: retain a source-native class handle when a later researcher could reconnect to it as a distinct item of that class without reconstructing it merely from grammar, a neighboring retained coordinate, or a broader canonical binding. Also allow a narrow necessary-support route for unnamed PLACE/TIME frames needed to keep materially distinct scenes/episodes from collapsing. For VERB/LABEL/LOCATOR, retain a distinct edge only when it remains independently useful after participants and broad scene/frame are known.

ACCOUNTED-FOR BUT NOT PRIMITIVE: suppress aliases/pronoun duplicates; auxiliaries/do-support/aspect/control/infinitival/copular/reporting scaffolding; phrase-internal prepositions and generic complements; frequency/sequencing fragments inside an existing episode; modifier/degree fragments already carried by a source-native value/quality; unreified proposition/event shells; local lexical fragments better carried by one complete relation handle; metadiscourse; alternate tokenizations; automatic cross-class shadows; or details fully preserved inside an admitted source phrase/cue or selective canonical compound without distinct class-native access.

LOW SALIENCE NEVER DISQUALIFIES A REAL HANDLE. One-use, remembered, reported, prospective, uncertain, negative, figurative, relational, or background material must still be considered.

DOMINANT PROJECTION: type by research job, not grammar. Spatial wording is not automatically PLACE/LOCATOR; temporal wording is not automatically TIME; a predicate is not automatically VERB; a modifier is not automatically LABEL; a noun phrase is not automatically OBJECT. Cross-class overlap is exceptional and requires two independently useful class-native handles.

PLACE: scene/interaction-scale physical/institutional settings and occurrence positions. Retain broad/contained settings when each adds navigation. Reconstruct unnamed PLACE (source_wording null, exact source_cue) for a distinct interaction, wait, report, remembered/comparison/object-location scene, or present reflection when its occurrence position would otherwise vanish or merge. Do not inventory every spatial noun/path/distance/deictic/body part/figurative expression as PLACE.

TIME: reconnectable episode/period frames: attempts or waits when they are distinct episodes, recurring spans, remembered/reported frames, prospective frames, relationship periods, comparison frames, present reflection/telling. Do not turn every action, duration, frequency word, sequencing phrase, temporal adverb, or subordinate clause into TIME. Reconstruct unnamed TIME when a distinct represented frame exists but is not separately named.

PERSON: retain B plus every distinct represented human/social actor or stable group after true coreference, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors. Suppress true aliases and nonreferential/rhetorical addressees.

OBJECT: source-reified concrete/abstract referents with independent identity: physical things, products/documents/parts, amounts/values, choices, decisions, plans, stable recurring relations/practices, relationships, represented sets/categories, comparison vehicles, and explicitly reified mental/content objects. Reject noun-phrase census, pronoun duplicates, unreified proposition/event shells, arbitrary fragments, and settings whose only job is PLACE.

LABEL: separately staged source value/state/classification/evaluation/comparison/correction/rejection/identity/manner/status/questioned value. Use shortest complete source-native span. Preserve negation, uncertainty, question, rejection/affirmation, contrast, and intensity. Do not merge successive source-staged postures merely because they concern one topic. Do not turn every adjective/degree/comparison fragment into LABEL; ordinary description may be qualities_available.

VERB: ADMISSION BEFORE SPLITTING. Retain a complete content-bearing relation/happening only when it remains a distinct research edge after participants/context are known. Do not inventory every matrix/control/embedded/reporting/copular predicate. Preserve particles, reflexives, negation, modal posture, and required complements when relation identity requires them. Split neighboring predicates only when they create genuinely different independently reconnectable relations with different research work/arguments/targets/states. Suppress auxiliaries, do-support, empty copulas, aspect/control scaffolding, generic reporting/telling scaffolding, redundant identity copulas already carried by LABEL, and support fragments.

LOCATOR: independent source-native orientation handle: position, containment, origin/destination, direction/path, entry/exit, proximity/distance, movement-course, accompaniment/carrying, recurring-context, or represented figurative/comparative orientation. Prefer smallest complete orientation phrase, not bare preposition. Do not inventory every recipient phrase, ownership/provenance phrase, temporal adverb, discourse connective, or phrase-internal complement. If orientation is fully carried by the admitted relation/compound and adds no distinct handle, keep it there rather than creating LOCATOR.

LITERAL LOCK: preserve source language character-for-character where source text is required. No synonym substitution, grammar repair, dialect normalization, number changes, contraction expansion, or punctuation cleanup. Only genuinely unnamed PLACE/TIME may use null source_wording with exact source_cue.

COREFERENCE/ORDER/QUALITIES: merge true coreferents. Order by first source establishment after coreference, with speaker-first PERSON and broad-before-contained setting navigation where supported. qualities_available is boolean only and never forces LABEL.

FREEZE PRIMITIVES BEFORE COMPOUNDS.

COMPOUNDS — SELECTIVE CANONICAL BINDINGS: build a compound only when at least two frozen primitives participate in one reconnectable source-local relation/state/orientation and binding them adds research value beyond viewing them separately. Use the admitted relation/value/orientation anchor, participants/referents, and only material scene/frame/orientation coordinates. A primitive may remain unbundled. Do NOT create one compound per proposition, sentence, predicate, or primitive; no pairwise closure, subset/superset variants, alternate tokenizations, grammatical-support bundles, mega-scenes, duplicates, or cross-proposition bundles. A compound cannot justify an otherwise non-entitled primitive.

FINAL AUDIT: every material detail accounted for? every primitive independently entitled? any explicit-word atomization? necessary unnamed scene/time frames preserved? source-reified choices/decisions/relations/contents preserved? value posture exact? VERBs complete but not predicate census? LOCATORs material but not preposition census? cross-class overlap independently justified? literal wording/coreference/order exact? compounds selective and local?

Never target hidden counts or infer hidden gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. The calibration worker must never access sealed holdout content or output.
'''.strip()

V87_CLASS_RULES = {
    "PLACE": r'''Return reconnectable scene/interaction-scale settings and necessary occurrence positions only. Preserve broad/contained settings when each adds navigation; reconstruct unnamed distinct interaction/wait/report/comparison/present positions when otherwise lost. Do not census spatial vocabulary, paths, objects, distance, deictics, or figurative phrases.'''.strip(),
    "TIME": r'''Return reconnectable episode/period frames, including necessary unnamed distinct frames. A local action, duration, frequency word, sequencing phrase, or temporal adverb does not become TIME merely because it is temporal. Prefer one useful frame over microframes unless the source truly stages distinct episodes.'''.strip(),
    "PERSON": r'''Retain B and each distinct represented human/social actor or stable group after true coreference, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors. Suppress aliases and nonreferential addressees.'''.strip(),
    "OBJECT": r'''Retain source-reified concrete/abstract referents with independent identity: real things, amounts, choices/decisions/plans, stable recurring relations/practices, relationships, represented sets, comparison vehicles, and reified mental/content objects. Reject noun-phrase census, pronoun duplicates, and unreified proposition/event shells.'''.strip(),
    "LABEL": r'''Retain separately staged source-native values/states/classifications/evaluations/comparisons/corrections/rejections/statuses/questioned values. Preserve question/negation/affirmation/uncertainty/contrast at exact source grain; do not merge separately staged postures. Reject modifier/degree census and ordinary description already carried as quality.'''.strip(),
    "VERB": r'''Admission precedes lexical splitting. Retain only a complete content-bearing relation that remains a distinct research edge after participants/context are known. Split neighboring predicates only when independently reconnectable relations differ in research work/arguments/targets/states. Suppress auxiliary/control/aspect/copular/reporting/support fragments and predicate census.'''.strip(),
    "LOCATOR": r'''Retain independently queryable source-native orientation: position, containment, origin/destination, path/direction, proximity/distance, movement-course, accompaniment, recurring-context, or represented comparison orientation. Prefer one smallest complete orientation phrase; reject preposition/recipient/ownership/temporal-adverb/context census and orientation already fully carried by another binding.'''.strip(),
}
