"""V88 semantic task rules: class-local independent coordinate grain."""

V88_BASE_RULES = r'''
V88 LIGHTWEIGHT RULE: CLASS-LOCAL INDEPENDENT COORDINATE GRAIN. Read the whole source, then evaluate EACH REQUESTED CLASS INDEPENDENTLY. Retain the smallest sufficient source-native coordinate when removing it from that requested class would erase a materially distinct reusable function of that class. The same wording may independently support more than one class when it does different research work. Cross-class overlap is neither automatic nor presumptively forbidden.

THIS IS AN INDEX, NOT INTERPRETATION AND NOT A GRAMMATICAL TOKEN CENSUS.

WHOLE-SOURCE WALK: consider actual, remembered, reported, relational, recurring, reflective, intended, questioned, hypothetical, negated, corrected, figurative, and prospective material. Low salience never defeats a genuine coordinate. Salience and grammar alone never create one.

CLASS-LOCAL GATE: for each candidate ask: IF REMOVED FROM THIS REQUESTED CLASS, WOULD A MATERIALLY DISTINCT FUNCTION OF THIS CLASS DISAPPEAR? If yes retain it. If no omit it. Do not omit a legitimate class coordinate merely because related wording appears in another class or compound. Remove true aliases, repeated mentions, alternate tokenization, and grammar-only support.

SMALLEST SUFFICIENT FUNCTIONAL GRAIN: do not atomize auxiliaries/articles/bare prepositions/inflection/support grammar. Do not merge neighboring lexical relations, orientations, occurrence positions, episode frames, values, or referents merely because they share a sentence, clause, scene, or proposition. Keep pieces together only when splitting destroys one source-native coordinate or produces grammar debris rather than distinct reusable jobs.

PLACE: materially useful site or occurrence-position. Retain broad and contained settings, relevant object positions/origin/destination positions, and positions of distinct waits, encounters, conversations, reports, remembered/comparison scenes, or present telling/reflection. Distinct episodes may have distinct unnamed PLACE coordinates even at the same physical venue when the occurrence-position is useful. Do not census every spatial noun/path/deictic/figurative expression. Unnamed PLACE may use source_wording null with exact source_cue.

TIME: materially distinct episode/period frame. Retain distinct attempts/conditions, response/help episodes, departures/transitions, waits, intended periods, later conversations/reports, recurring spans, relationship periods, remembered/comparison frames, present reflection/telling, and separately staged prospective frames. Several actions can share one TIME, but split when the source materially stages a new episode/period. Temporal words/durations/frequency/tense alone do not create TIME. Unnamed TIME may use source_wording null with exact source_cue.

PERSON: B plus every distinct represented human/social actor or stable group after true coreference when the source gives a distinguishable participant, relational, reported, remembered, prospective, or institutional role. Minor/offscreen/possessive-relational actors may qualify. Suppress true aliases and nonreferential/rhetorical addressees.

OBJECT: source-treated concrete or abstract thing with independent selectable identity: physical things/parts, products/documents/services/results, amounts/values, choices/decisions/plans/next steps treated as things, stable recurring relations/practices/relationships treated as objects of concern, represented sets/categories, comparison vehicles, and explicitly reified mental/content objects. Do not nominalize an unreified event/proposition/clause/intention/question/relation merely to create coverage. A noun phrase is not automatically OBJECT.

LABEL: separately staged source characterization/value/state/classification/evaluation/comparison/identity/manner/status/correction/rejection/questioned value. Use shortest complete exact source span; preserve negation, uncertainty, question, contrast, rejection/correction, and intensity when needed. Do not suppress a real LABEL because same wording participates in another class or qualities_available. qualities_available never substitutes for a materially distinct LABEL.

VERB — LEXICAL PREDICATE INCREMENTS: inventory materially represented lexical predicate increments in source order. Use the SMALLEST COMPLETE lexical predicate construction preserving a distinct happening/state/stance/cognition/report/relation and posture. Split matrix + embedded predicates when each has a different independently selectable predicate job. Split coordinated/sequential predicates when each does different work. Retain source-present seeing/saying/thinking/finding/asking/telling/trying/meaning/reporting/cognition when those acts are materially represented and independently reconnectable. Preserve particles/reflexives/negation/modal posture/required complements needed for predicate identity. Keep a semantically bound multiword predicate together when pieces do not independently do different jobs. Motion wording may independently support VERB and LOCATOR. Suppress pure auxiliaries/do-support and quality copula duplicates whose only content is an already-retained LABEL. Do NOT replace several independently useful lexical predicates with one clause-sized relation.

LOCATOR: independently useful where/which-position/which-path/which-context/orientation relation. Retain broad/contained setting relations, position/proximity, origin/destination, movement/path, entry/exit, accompaniment/carrying when locational, containment, recurring/situational context, and internal/figurative/comparative orientation. Use smallest complete meaningful construction, not bare preposition. Evaluate independently from PLACE/TIME/VERB/OBJECT/compound. Do NOT suppress genuine orientation merely because its wording already occurs in a motion verb, place, time, or compound. Suppress routine possession/recipient/topic marking and phrase-internal prepositions with no independent orientation/context job.

LITERAL LOCK: preserve source language character-for-character where source text is required. No synonym substitution, grammar repair, dialect normalization, number changes, contraction expansion, or punctuation cleanup. Only genuinely unnamed PLACE/TIME may use null source_wording with exact source_cue. researcher_note should be null/minimal mechanical bookkeeping, not interpretation.

COREFERENCE/ORDER/QUALITIES: merge true coreferents; default to first material source anchor after filtering/coreference, speaker-first PERSON, broad-before-contained setting navigation where supported. qualities_available is boolean only and neither forces nor suppresses LABEL.

FREEZE PRIMITIVES BEFORE COMPOUNDS.

COMPOUNDS — PROPOSITION-LEVEL MAP: create a compound for each materially distinct represented proposition, situation, predicate relation, characterization proposition, question, correction, comparison, reflection, or prospective relation useful for reconnection, using only frozen units. Prefer proposition/event-level coverage over a few broad scene summaries. Split materially different propositions. A source sentence may yield several compounds. Do not create grammar-fragment compounds, duplicate alternate tokenizations, arbitrary pairwise closure, or compounds merely because a primitive exists. Compounds cannot repair missing primitives.

FINAL AUDIT: whole source read? each class evaluated independently? removing each retained primitive would remove a distinct class function? any legitimate coordinate suppressed because of cross-class overlap? aliases/grammar debris removed? distinct PLACE/TIME occurrence frames retained without microframe census? OBJECT source-reified not proposition-shell? LABEL posture exact? VERBs smallest complete lexical increments rather than clause summaries/token census? LOCATOR independently preserves material orientation/context? literal wording/coreference/order exact? compounds proposition-level using frozen units only?

Never target hidden counts or infer hidden gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. The calibration worker must never access sealed holdout content or output.
'''.strip()

V88_CLASS_RULES = {
    "PLACE": r'''Return materially useful sites and occurrence-positions. Preserve broad/contained settings and distinct wait/encounter/conversation/report/remembered/comparison/present-telling positions, including unnamed positions even when physically overlapping another place if removing the coordinate loses episode navigation. Do not census spatial vocabulary.'''.strip(),
    "TIME": r'''Return materially distinct episode/period frames: attempts, response/help episodes, transitions/departures, waits, intended periods, later reports/conversations, recurring spans, relationship periods, remembered/comparison frames, present reflection, and separately staged prospective frames. Several actions can share one frame; split when the represented episode/period materially changes. Do not census temporal words.'''.strip(),
    "PERSON": r'''Retain B and each distinct represented human/social actor or stable group after true coreference, including minor, relational, offscreen, remembered, reported, prospective, and institutional actors when they have an independent participant/relational job. Suppress aliases and nonreferential addressees.'''.strip(),
    "OBJECT": r'''Retain source-treated independently selectable concrete/abstract referents: physical things/parts, products/documents/services/results, amounts, choices/decisions/plans/next steps treated as things, stable relations/practices/relationships treated as objects, sets/categories, comparison vehicles, and reified mental/content objects. Reject pronoun duplicates, noun-phrase census, and unreified proposition/event shells.'''.strip(),
    "LABEL": r'''Retain independently reusable source characterizations/values/states/classifications/evaluations/comparisons/identity/manner/status/corrections/rejections/questioned values. Use shortest complete exact wording and preserve posture. Evaluate independently from qualities and other classes; do not suppress merely because same wording also supports another class.'''.strip(),
    "VERB": r'''Inventory materially represented lexical predicate increments in source order at the smallest complete functional grain. Split matrix/embedded and coordinated/sequential predicates when each contributes a distinct reconnectable relation; retain source-present reporting/cognition acts when independently represented; preserve particles/negation/modal/required complements needed for predicate identity; keep inseparable multiword predicates together; suppress pure auxiliaries/do-support and grammar-only/copula duplicates. Do not compress several distinct predicates into one clause-sized relation.'''.strip(),
    "LOCATOR": r'''Retain independently useful source-native orientation/context: broad/contained setting relation, position/proximity, origin/destination, path/movement, entry/exit, accompaniment/carrying when locational, containment, recurring context, and figurative/comparative/internal orientation. Evaluate independently from PLACE/TIME/VERB/compound and allow overlapping wording when it performs a real locator job. Use smallest complete phrase, not bare preposition; reject routine argument/possession/preposition census.'''.strip(),
}
