"""V89 semantic task rules: primitive entitlement first, then minimal class-head grain."""

V89_BASE_RULES = r'''
V89 LIGHTWEIGHT RULE: PRIMITIVE ENTITLEMENT FIRST; THEN MINIMAL CLASS-HEAD GRAIN.

Read the whole source before extracting any class. Consider every material coordinate, but emit a standalone primitive only when it remains an independently reconnectable class-native handle after its participants, arguments, qualities, support grammar, broader scene/frame, and local compound binding are accounted for. Once a primitive is entitled, use the smallest complete source-native class-head wording that preserves its identity. Do not absorb separable PERSON/OBJECT/PLACE/TIME/LABEL/LOCATOR arguments merely to make a phrase read like a complete clause.

THIS IS AN INDEX, NOT INTERPRETATION AND NOT A TOKEN/GRAMMAR/MODIFIER/PREPOSITION CENSUS.

WHOLE-SOURCE LEDGER: consider actual, remembered, reported, relational, recurring, reflective, intended, questioned, hypothetical, negated, corrected, figurative, and prospective material. Accounting for material does not automatically entitle it to a primitive.

CLASS-NATIVE ENTITLEMENT TEST: ask (1) after participants, arguments, broad scene/frame, qualities, and neighboring coordinates are known, does this candidate still provide a distinct research handle of this requested class? and (2) if omitted from this class, would a materially distinct class-native function disappear rather than remain represented in another primitive's exact wording/cue or a canonical local compound? Retain only when both are yes, except required unnamed PLACE/TIME support frames.

TYPE/SHADOW AUDIT: type by the actual research job. Cross-class overlap is allowed only when each projection independently survives the entitlement test. Shared wording or mixed grammatical content alone does not justify multiple primitives.

MINIMAL CLASS-HEAD GRAIN: once entitled, retain the smallest complete source-native wording that preserves identity. Keep required particles, reflexives, modal/negative posture, or required complements when removing them changes the handle. Keep separable participants, objects, places, times, labels, and locators in their own coordinates.

GENERAL NON-ENTITLEMENT: suppress aliases/repeated mentions/alternate tokenization; auxiliaries/do-support/empty copulas/tense-aspect/control support; routine arguments already represented in their own class; modifiers/degree phrases adequately carried as qualities; temporal/sequencing fragments that merely locate a broader episode; phrase-internal prepositions or complements without independent orientation; unreified event/proposition/clause shells; metadiscourse; cross-class shadows whose job disappears once the dominant coordinate and local compound are known. Low salience alone never defeats a real handle.

PLACE: materially useful site or necessary occurrence-position. Retain broad and contained settings when each independently supports navigation. Reconstruct an unnamed PLACE only when a distinct interaction, wait, report, remembered/comparison scene, object-location scene, or present telling/reflection would otherwise collapse into another occurrence context. Do not census spatial nouns, surfaces, paths, distances, objects, communities, water/forest/boat mentions, deictics, or figurative phrases. Concrete object/destination positions may qualify when independently useful; use the smallest place wording or unnamed support position, not the whole clause.

TIME: materially distinct episode/period frame that can be independently revisited. Retain distinct attempts/conditions, response/help episodes, departures/transitions, waits, intended periods, later conversations/reports, recurring spans, relationship periods, remembered/comparison frames, present telling/reflection, and separately staged prospective frames when the frame itself remains useful. Do not create TIME from every action, duration, tense, frequency marker, sequence phrase, or temporal clause. Several actions may share one frame; split only when the represented episode/period materially changes.

PERSON: retain B plus each distinct represented human/social actor or stable group after true coreference when the actor has an independent participant, relational, reported, remembered, prospective, or institutional role. Minor/offscreen/possessive-relational actors may qualify. Suppress true aliases and nonreferential/rhetorical addressees.

OBJECT: source-treated concrete or abstract thing with independent selectable identity. Retain physical things/parts, products/documents/services/results, amounts/values, choices/decisions/plans/next steps treated as things, stable recurring relations/practices/relationships treated as objects of concern, represented sets/categories, comparison vehicles, and explicitly reified mental/content objects. Do not admit every noun phrase, unreified event/proposition/question/relation/modifier/clause, or duplicate a PLACE/LABEL whose only job belongs there. For descriptive phrases, keep the OBJECT head separate from an independently entitled LABEL only when each remains separately selectable.

LABEL: independently staged characterization/value/state/classification/evaluation/comparison/identity/manner/status/correction/rejection/questioned candidate value. This is not adjective/modifier census. Ordinary description may remain qualities_available only. Use the shortest complete exact wording that preserves posture; keep negation, uncertainty, question, contrast, rejection/correction, and intensity when needed. Candidate value and explicit response may split when the source stages them separately. Do not create LABEL from whole propositions/questions merely because they contain evaluation, or from noun/categories better typed PERSON/OBJECT/PLACE.

VERB: relation entitlement first, then minimal lexical predicate head. Retain a happening/state/stance/cognition/report only when it remains an independent research edge after participants, arguments, scene/frame, values, and orientation are known. Do not automatically split every matrix/control/aspect predicate and embedded predicate; split only when each independently passes entitlement. Coordinated/sequential predicates may split when each contributes a different edge. Reporting/cognition acts qualify only when independently represented rather than mere scaffolding. Once entitled, exclude separable subject/object/PLACE/TIME/LOCATOR/LABEL arguments from source_wording/tag unless required to identify the predicate. Preserve particles/required complements when removing them changes relation identity; preserve modal/negative posture when identity-relevant. Suppress auxiliaries, do-support, empty copulas, and support/control fragments that fail entitlement. Do not expand a relation head to the whole clause for grammatical completeness.

LOCATOR: independently selectable where/from/toward/path/containment/context/orientation relation. Retain broad/contained setting relations, position/proximity, origin/destination, movement/path, entry/exit, accompaniment/carrying when locational, containment, recurring/situational context, and genuine internal/figurative/comparative orientation when the orientation itself remains useful after PLACE/TIME and relation arguments are known. Use smallest complete meaningful construction, not bare preposition or whole clause when smaller wording preserves the job. Movement VERB and LOCATOR may overlap only when each independently survives entitlement. Suppress routine possession, recipient/beneficiary/topic/provenance, temporal adverbial material, and phrase-internal prepositions without independent orientation.

LITERAL LOCK: preserve source language character-for-character wherever source text is required. No grammar repair, dialect normalization, synonym substitution, number changes, contraction expansion, or punctuation cleanup. Only genuinely unnamed PLACE/TIME support frames may use null source_wording with exact source_cue. researcher_note should be null or minimal mechanical/coreference bookkeeping.

COREFERENCE/ORDER/QUALITIES: merge true coreferents; order by first material source establishment after filtering/coreference, with speaker-first PERSON and broad-before-contained setting navigation where supported. qualities_available is boolean only and neither forces nor suppresses LABEL.

FREEZE PRIMITIVES BEFORE COMPOUNDS. Audit entitlement, actual class job, minimal class-head wording, separable arguments/context, and cross-class shadows before freezing.

COMPOUNDS: create the smallest materially useful local bindings that reconnect admitted coordinates to represented source relations/states/orientations. Use frozen coordinates only. Bind the admitted relation/value/orientation anchor, participating PERSON/OBJECT coordinates, and only materially belonging PLACE/TIME/LOCATOR coordinates. Avoid grammar fragments, pairwise closure, duplicate subset/superset variants, scene mega-bundles, compounds created merely because a primitive exists, or any compound containing a primitive whose only reason for existence is that compound. A sentence may yield several compounds if it contains several independently represented relations.

FINAL AUDIT: whole source read? each primitive independently entitled? type reflects actual class job? overlap independently justified? PLACE/TIME preserve necessary frames without census? OBJECT source-reified? LABEL staged value not modifier census? VERB entitlement precedes splitting and uses minimal complete predicate head? LOCATOR independently useful not preposition census? literal wording/coreference/order exact? separable arguments/context not absorbed merely for grammatical completeness? compounds use frozen units only? candidate-only boundary preserved?

Never target hidden counts or infer hidden gold. Never perform APA scoring, psychological interpretation, promotion, APA-ID creation, sovereign/admitted writing, or database mutation. The calibration worker must never access sealed holdout content or output.
'''.strip()

V89_CLASS_RULES = {
    "PLACE": r'''Return only independently useful sites or necessary occurrence-positions. Admit broad/contained settings when each survives the class-native entitlement test, plus unnamed support positions when a distinct interaction/wait/report/remembered/comparison/present-telling scene would otherwise collapse. Do not census spatial vocabulary, object surfaces, paths, distance phrases, or figurative locations. Use minimal place wording, not whole clauses.'''.strip(),
    "TIME": r'''Return only independently revisit-able episode/period frames: distinct attempts/conditions, response/help episodes, transitions, waits, intended periods, reports/conversations, recurring spans, relationship periods, remembered/comparison frames, present reflection, and prospective frames. Do not census actions, tense, duration, frequency, or sequencing fragments. Use the smallest named temporal handle or an unnamed exact-cue frame.'''.strip(),
    "PERSON": r'''Retain B and each distinct represented human/social actor or stable group after true coreference when it has an independent participant/relational role, including minor, offscreen, remembered, reported, prospective, and institutional actors. Suppress true aliases and nonreferential addressees.'''.strip(),
    "OBJECT": r'''Retain source-treated independently selectable things/content: physical things/parts, products/documents/services/results, amounts, choices/decisions/plans treated as things, stable relations/practices/relationships treated as objects, sets/categories, comparison vehicles, and explicitly reified mental/content objects. Reject noun-phrase census, unreified clause/event/proposition shells, and PLACE/LABEL shadows. Prefer the object head over an entire descriptive proposition.'''.strip(),
    "LABEL": r'''Retain only independently staged values/states/characterizations/classifications/evaluations/comparisons/identity/manner/status/corrections/rejections/questioned candidate values. Ordinary modifiers may remain qualities only. Use the shortest complete exact source wording preserving posture; do not turn whole propositions/questions or noun categories into LABEL merely because they contain evaluation.'''.strip(),
    "VERB": r'''First decide whether the relation itself remains an independently selectable research edge after participants/arguments/context are known. Only then choose the smallest complete lexical predicate head. Split matrix/embedded or coordinated predicates only when each independently passes entitlement. Keep identity-changing particles/required complements/modal/negative posture; exclude separable PERSON/OBJECT/PLACE/TIME/LABEL/LOCATOR arguments. Suppress auxiliaries, do-support, empty copulas, and support/control scaffolding. Do not expand to clause-sized wording for grammatical completeness.'''.strip(),
    "LOCATOR": r'''Retain only independently useful orientation/context handles: setting relation, position/proximity, origin/destination, path/movement, entry/exit, containment, locational accompaniment/carrying, recurring context, or genuine figurative/comparative/internal orientation. Use the smallest complete meaningful construction. Allow overlap with VERB/PLACE only when the locator job independently survives entitlement. Reject possession, recipient/beneficiary/topic/provenance, temporal adverbial, and phrase-internal preposition census.'''.strip(),
}
